/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA;
typedef struct tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg;
typedef struct tySequence__1Ib9a4sxiw4YCYbDTADLEsg tySequence__1Ib9a4sxiw4YCYbDTADLEsg;
typedef struct tySequence__xxWWYOndkW9adiM61bZkvsg tySequence__xxWWYOndkW9adiM61bZkvsg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw;
typedef struct tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g;
typedef struct tySequence__mAI4KvRAgoko9bmrV4QRgaQ tySequence__mAI4KvRAgoko9bmrV4QRgaQ;
typedef struct tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg;
typedef struct tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw;
typedef struct tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig;
typedef struct tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w;
typedef struct tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw;
typedef struct tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA;
typedef struct tyObject_PyObject_HEAD_EXTRA__AZfyXx4FzGJVoO01VjoS9cw tyObject_PyObject_HEAD_EXTRA__AZfyXx4FzGJVoO01VjoS9cw;
typedef struct tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ;
typedef struct tyObject_PyIterRefcolonObjectType___d9bsBVvwpaMgkPbcqU7T9apw tyObject_PyIterRefcolonObjectType___d9bsBVvwpaMgkPbcqU7T9apw;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg;
typedef struct tyObject_PyModuleDef_Base__rlCDhfYMTJl9bANneNOHAGQ tyObject_PyModuleDef_Base__rlCDhfYMTJl9bANneNOHAGQ;
typedef struct tyObject_PyModuleDef_Slot__vPt0O09cLIJL9aVVlDCzVeRA tyObject_PyModuleDef_Slot__vPt0O09cLIJL9aVVlDCzVeRA;
typedef struct tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA {
NCSTRING name;
NCSTRING doc;
tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg* methods;
tySequence__1Ib9a4sxiw4YCYbDTADLEsg* types;
tySequence__xxWWYOndkW9adiM61bZkvsg* iterators;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_CDECL_PTR(void*, tyProc__uQWqJp3WAx8fOY1h9aCwjIg) (void* s, void* a, void* k);
struct tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw {
NCSTRING ml_name;
tyProc__uQWqJp3WAx8fOY1h9aCwjIg ml_meth;
int ml_flags;
NCSTRING ml_doc;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void*, tyProc__eYT4U6bGFqFBUxk9b15mfOA) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* typ, void* a, void* b);
struct tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg {
tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* module;
NCSTRING name;
NCSTRING doc;
NimStringDesc* fullName;
tyProc__eYT4U6bGFqFBUxk9b15mfOA newFunc;
tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg* methods;
tySequence__mAI4KvRAgoko9bmrV4QRgaQ* members;
NI origSize;
};
struct tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg {
NCSTRING name;
int typ;
NI offset;
int flags;
NCSTRING doc;
};
struct tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw {
NCSTRING name;
NCSTRING doc;
tyProc__eYT4U6bGFqFBUxk9b15mfOA newFunc;
};
typedef N_CDECL_PTR(void*, tyProc__SsjMo29bx9bP5kwe2xgM3Scg) (NCSTRING f, ...);
typedef N_CDECL_PTR(void*, tyProc__4wJmT85lsn175X0dPNQv7w) (NI sz);
typedef N_CDECL_PTR(NI, tyProc__YRQqZC12s3573tRGP8MV3g) (void* f);
typedef N_CDECL_PTR(void*, tyProc__oPIasAghCTvCKmvkMeB1xQ) (void* f, NI i);
typedef N_CDECL_PTR(int, tyProc__6slETyyIDJuDOSqkO0hUXA) (void* f, NI i, void* v);
typedef N_CDECL_PTR(int, tyProc__tgpXIILGoVcO9bvYnz9azTVQ) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* f);
typedef N_CDECL_PTR(int, tyProc__T08W9bgbY4bOv2q64h6irpw) (void* m, NCSTRING n, void* o);
typedef N_CDECL_PTR(int, tyProc__fbYpjfe38x3ujjAmVRbI1Q) (void* o);
typedef N_CDECL_PTR(void*, tyProc__YezmFzxOOyM9cb11Eoq1Elg) (void* o, NCSTRING name);
typedef N_CDECL_PTR(void*, tyProc__jvPpjMAkI9bwM1B9apOphnlA) (void* o);
typedef N_CDECL_PTR(void*, tyProc__VQ1ysQk017myXMGb79cPTVw) (void* o, void* k);
typedef N_CDECL_PTR(int, tyProc__7LMjBc4zOHVIsNdulNv7QQ) (void* o, void* k, void* v);
typedef N_CDECL_PTR(int, tyProc__eoRP3F9aLT3mtHj6OkcMSyQ) (void* a, void* b, int op);
typedef N_CDECL_PTR(int, tyProc__8hR9arLDkUs9ag3Pt9bWtjfsg) (void* o, tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w* b, int flags);
typedef N_CDECL_PTR(void, tyProc__vFvpnKOere9bRFN9czzMRlTA) (tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w* b);
typedef N_CDECL_PTR(void*, tyProc__BZ6N5NNdHcK05FTDxQbEWw) (NCSTRING name, void* base, void* dict);
typedef N_CDECL_PTR(NI64, tyProc__mIlNZ9aGaphVJCyIIofK8mg) (void* l);
typedef N_CDECL_PTR(double, tyProc__2su9b9chqHYibM7sMkbSaSkA) (void* l);
typedef N_CDECL_PTR(void*, tyProc__Fc4ZUx59aQs10dLxeMQ50mw) (long v);
typedef N_CDECL_PTR(int, tyProc__i2exZ7Vtp648U9crOFcq9beQ) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* t1, tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* t2);
struct tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA {
NF re;
NF im;
};
typedef N_CDECL_PTR(tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA, tyProc__N1A5ZvDSgO9c9aRXmVqfn9bAw) (void* op);
typedef N_CDECL_PTR(int, tyProc__3FKLKFzOaK7FD6dRLWM6Jw) (void* o, NIM_CHAR** s, NI* len);
typedef N_CDECL_PTR(void*, tyProc__YDKrw1adv61oVQkQhbYyaA) (NCSTRING s);
typedef N_CDECL_PTR(int, tyProc__B2MjSeo07a72ynTQRVYFKw) (void* o, NCSTRING s);
typedef N_CDECL_PTR(NCSTRING, tyProc__p1X2BwWx9a3wsChhykvf29aA) (void* o);
typedef N_CDECL_PTR(void*, tyProc__NzboHqZVJcbdtVGYrOosXQ) (void);
typedef N_CDECL_PTR(int, tyProc__MTei9bsKjha0o1cISO9aLMDg) (void* o, void* k);
typedef N_NIMCALL_PTR(void, tyProc__4SVlZZPmetqBimNsH9cHcOA) (void* o);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc__WYY8i0I79agBofnUcEGCfig) (void* o, NCSTRING s);
typedef N_CDECL_PTR(void, tyProc__32w2ZypAyMWuajvi2Jt79cg) (void* o);
typedef N_CDECL_PTR(void*, tyProc__jcEovQ2rZUNUsYxohT50Ug) (void* p, NCSTRING name, tyProc__32w2ZypAyMWuajvi2Jt79cg destr);
typedef N_CDECL_PTR(void*, tyProc__9b2qzlf3LCKK0JvThQT1atg) (tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw* md, void* self, void* module);
typedef N_CDECL_PTR(void, tyProc__U0oVFt576Ze44Q9a3eZc5wg) (void** ptype, void** pvalue, void** ptraceback);
struct tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig {
void* module;
tyProc__SsjMo29bx9bP5kwe2xgM3Scg Py_BuildValue;
tyProc__4wJmT85lsn175X0dPNQv7w PyTuple_New;
tyProc__YRQqZC12s3573tRGP8MV3g PyTuple_Size;
tyProc__oPIasAghCTvCKmvkMeB1xQ PyTuple_GetItem;
tyProc__6slETyyIDJuDOSqkO0hUXA PyTuple_SetItem;
void* Py_None;
tyProc__tgpXIILGoVcO9bvYnz9azTVQ PyType_Ready;
tyProc__eYT4U6bGFqFBUxk9b15mfOA PyType_GenericNew;
tyProc__T08W9bgbY4bOv2q64h6irpw PyModule_AddObject;
tyProc__4wJmT85lsn175X0dPNQv7w PyList_New;
tyProc__YRQqZC12s3573tRGP8MV3g PyList_Size;
tyProc__oPIasAghCTvCKmvkMeB1xQ PyList_GetItem;
tyProc__6slETyyIDJuDOSqkO0hUXA PyList_SetItem;
tyProc__uQWqJp3WAx8fOY1h9aCwjIg PyObject_Call;
tyProc__fbYpjfe38x3ujjAmVRbI1Q PyObject_IsTrue;
tyProc__YezmFzxOOyM9cb11Eoq1Elg PyObject_GetAttrString;
tyProc__T08W9bgbY4bOv2q64h6irpw PyObject_SetAttrString;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyObject_Dir;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyObject_Str;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyObject_GetIter;
tyProc__VQ1ysQk017myXMGb79cPTVw PyObject_GetItem;
tyProc__7LMjBc4zOHVIsNdulNv7QQ PyObject_SetItem;
tyProc__eoRP3F9aLT3mtHj6OkcMSyQ PyObject_RichCompareBool;
tyProc__8hR9arLDkUs9ag3Pt9bWtjfsg PyObject_GetBuffer;
tyProc__vFvpnKOere9bRFN9czzMRlTA PyBuffer_Release;
tyProc__BZ6N5NNdHcK05FTDxQbEWw PyErr_NewException;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyIter_Next;
tyProc__mIlNZ9aGaphVJCyIIofK8mg PyLong_AsLongLong;
tyProc__2su9b9chqHYibM7sMkbSaSkA PyFloat_AsDouble;
tyProc__Fc4ZUx59aQs10dLxeMQ50mw PyBool_FromLong;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyFloat_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyComplex_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyCapsule_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyTuple_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyList_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyBytes_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyUnicode_Type;
tyProc__i2exZ7Vtp648U9crOFcq9beQ PyType_IsSubtype;
tyProc__N1A5ZvDSgO9c9aRXmVqfn9bAw PyComplex_AsCComplex;
tyProc__2su9b9chqHYibM7sMkbSaSkA PyComplex_RealAsDouble;
tyProc__2su9b9chqHYibM7sMkbSaSkA PyComplex_ImagAsDouble;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyUnicode_AsUTF8String;
tyProc__3FKLKFzOaK7FD6dRLWM6Jw PyBytes_AsStringAndSize;
tyProc__YDKrw1adv61oVQkQhbYyaA PyUnicode_FromString;
tyProc__B2MjSeo07a72ynTQRVYFKw PyUnicode_CompareWithASCIIString;
tyProc__p1X2BwWx9a3wsChhykvf29aA PyString_AsString;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyDict_Type;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyDict_New;
tyProc__YRQqZC12s3573tRGP8MV3g PyDict_Size;
tyProc__YezmFzxOOyM9cb11Eoq1Elg PyDict_GetItemString;
tyProc__T08W9bgbY4bOv2q64h6irpw PyDict_SetItemString;
tyProc__VQ1ysQk017myXMGb79cPTVw PyDict_GetItem;
tyProc__7LMjBc4zOHVIsNdulNv7QQ PyDict_SetItem;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyDict_Keys;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyDict_Values;
tyProc__MTei9bsKjha0o1cISO9aLMDg PyDict_Contains;
tyProc__4SVlZZPmetqBimNsH9cHcOA PyDealloc;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ PyErr_Clear;
tyProc__WYY8i0I79agBofnUcEGCfig PyErr_SetString;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyErr_Occurred;
void* PyExc_TypeError;
tyProc__jcEovQ2rZUNUsYxohT50Ug PyCapsule_New;
tyProc__YezmFzxOOyM9cb11Eoq1Elg PyCapsule_GetPointer;
tyProc__YDKrw1adv61oVQkQhbYyaA PyImport_ImportModule;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyEval_GetBuiltins;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyEval_GetGlobals;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyEval_GetLocals;
tyProc__9b2qzlf3LCKK0JvThQT1atg PyCFunction_NewEx;
NI pythonVersion;
tyProc__U0oVFt576Ze44Q9a3eZc5wg PyErr_Fetch;
tyProc__U0oVFt576Ze44Q9a3eZc5wg PyErr_NormalizeException;
tyProc__MTei9bsKjha0o1cISO9aLMDg PyErr_GivenExceptionMatches;
void* PyExc_BaseException;
void* PyExc_Exception;
void* PyExc_ArithmeticError;
void* PyExc_FloatingPointError;
void* PyExc_OverflowError;
void* PyExc_ZeroDivisionError;
void* PyExc_AssertionError;
void* PyExc_OSError;
void* PyExc_IOError;
void* PyExc_ValueError;
void* PyExc_EOFError;
void* PyExc_MemoryError;
void* PyExc_IndexError;
void* PyExc_KeyError;
void* NimPyException;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(void*, tyProc__2ujOETN3z9btuXStkbh8Cdg) (NCSTRING name, tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw* methods, NCSTRING doc, void* self, int apiver);
struct tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg {
NI ob_refcnt;
void* ob_type;
};
struct tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw {
  tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg Sup;
NI ob_size;
};
typedef N_CDECL_PTR(int, tyProc__rNiGphbUW4RHd2WIj64deg) (void* o, FILE* f, int c);
typedef N_CDECL_PTR(void*, tyProc__k4RBH32nrpDxtGF9acg45zw) (void* a, void* b, int c);
typedef N_CDECL_PTR(void*, tyProc__Cj3MN9a7OA9a51xOtsYjEwBg) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* typ, NI sz);
struct tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g {
  tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw Sup;
NCSTRING tp_name;
NI tp_basicsize;
NI tp_itemsize;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_dealloc;
tyProc__rNiGphbUW4RHd2WIj64deg tp_print;
tyProc__YezmFzxOOyM9cb11Eoq1Elg tp_getattr;
tyProc__T08W9bgbY4bOv2q64h6irpw tp_setattr;
void* tp_as_async;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_repr;
void* tp_as_number;
void* tp_as_sequence;
void* tp_as_mapping;
void* tp_hash;
void* tp_call;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_str;
tyProc__VQ1ysQk017myXMGb79cPTVw tp_getattro;
tyProc__7LMjBc4zOHVIsNdulNv7QQ tp_setattro;
void* tp_as_buffer;
unsigned long tp_flags;
NCSTRING tp_doc;
void* tp_traverse;
void* tp_clear;
tyProc__k4RBH32nrpDxtGF9acg45zw tp_richcompare;
NI tp_weaklistoffset;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_iter;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_iternext;
tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw* tp_methods;
tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg* tp_members;
void* tp_getset;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* tp_base;
void* tp_dict;
tyProc__uQWqJp3WAx8fOY1h9aCwjIg tp_descr_get;
tyProc__7LMjBc4zOHVIsNdulNv7QQ tp_descr_set;
NI tp_dictoffset;
tyProc__7LMjBc4zOHVIsNdulNv7QQ tp_init;
tyProc__Cj3MN9a7OA9a51xOtsYjEwBg tp_alloc;
tyProc__eYT4U6bGFqFBUxk9b15mfOA tp_new;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_free;
void* tp_is_gc;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* tp_bases;
void* tp_mro;
void* tp_cache;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* tp_subclasses;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* tp_weaklist;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_del;
unsigned int tp_version_tag;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_finalize;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_PyObject_HEAD_EXTRA__AZfyXx4FzGJVoO01VjoS9cw {
void* ob_next;
void* ob_prev;
};
struct tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA {
TNimType* m_type;
tyObject_PyObject_HEAD_EXTRA__AZfyXx4FzGJVoO01VjoS9cw py_extra_dont_use;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg py_object;
};
struct tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ {
  tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw Sup;
tyObject_PyIterRefcolonObjectType___d9bsBVvwpaMgkPbcqU7T9apw* iRef;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
typedef struct {
N_NIMCALL_PTR(void*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__KUkKMDDIR7OpocD9a4Oh3aQ;
struct tyObject_PyIterRefcolonObjectType___d9bsBVvwpaMgkPbcqU7T9apw {
tyProc__KUkKMDDIR7OpocD9a4Oh3aQ iter;
};
typedef N_CLOSURE_PTR(void*, TM__LoH0foxqckmmftA2y2Dp9aw_10) (void);
typedef N_CDECL_PTR(void*, tyProc__BEMKLd49c5qNHqmldA6aVaw) (void* m, int apiver);
struct tyObject_PyModuleDef_Base__rlCDhfYMTJl9bANneNOHAGQ {
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg ob_base;
tyProc__NzboHqZVJcbdtVGYrOosXQ m_init;
NI m_index;
void* m_copy;
};
struct tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg {
tyObject_PyModuleDef_Base__rlCDhfYMTJl9bANneNOHAGQ m_base;
NCSTRING m_name;
NCSTRING m_doc;
NI m_size;
tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw* m_methods;
tyObject_PyModuleDef_Slot__vPt0O09cLIJL9aVVlDCzVeRA* m_slots;
void* m_traverse;
void* m_clear;
void* m_free;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
  Exception Sup;
};
struct tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg {
  TGenericSeq Sup;
  tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw data[SEQ_DECL_SIZE];
};
struct tySequence__mAI4KvRAgoko9bmrV4QRgaQ {
  TGenericSeq Sup;
  tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg data[SEQ_DECL_SIZE];
};
struct tySequence__1Ib9a4sxiw4YCYbDTADLEsg {
  TGenericSeq Sup;
  tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg data[SEQ_DECL_SIZE];
};
struct tySequence__xxWWYOndkW9adiM61bZkvsg {
  TGenericSeq Sup;
  tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__mAI4KvRAgoko9bmrV4QRgaQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__1Ib9a4sxiw4YCYbDTADLEsg)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__xxWWYOndkW9adiM61bZkvsg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, initCommon__QOPr6RYgxP9c8n2lZVbiDwA_2)(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*, loadPyLibFromThisProcess__RtM7ZRu1XQXT9bXM8dFhSWgpy_lib)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*, loadPyLibFromModule__bRaZxNTpbKALHcCxxa9aNCA)(void* m);
static N_INLINE(void*, pythonLibHandleForThisProcess__qoq1L3DB9cXw9c9bTTVSl8S0gpy_lib)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__3W0xEugBG13TxVu4hk9b9b5g)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr);
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__Y66tOYFjgwJ0k4aLz4bc0Q)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__ALH9bdNwXEzg7MPq4PA9csvw)(void* lib, NCSTRING name);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, initModuleTypes__csb2z5UIH3D9cgBHISzH54g)(void* p, tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(void*, pyAlloc__1Aee2onoqwg9aFJWAasp3iAnimpy)(NI sz);
N_LIB_PRIVATE N_NOCONV(void*, alloc0__WrVG9abV9chlTLqkiXYLKwUg)(NI size);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*, to__5tJl9a9cvcVqYJFbXrlgYbfApy_lib)(void* p);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_CDECL(void, freeNimObj__jz2epPJWRa0T6WbzV9cD4Og)(void* p);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_CDECL(void, destructNimObj__5aiupm4TAhj22Yu9cWwwuVg)(void* o);
static N_INLINE(tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA*, toNim__BNt3aWEMNlje8KgYqFe8Vwnimpy)(void* p);
N_NIMCALL(void, nimGCunref)(void* p);
static N_INLINE(void, incRef__CnqcscfOCAX2jCHv3dRPDwpy_utils)(void* p);
static N_INLINE(tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*, to__4gaYCHYBaCTIs6wfSrqsEApy_lib)(void* p);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_CDECL(void, destructNimIterator__5aiupm4TAhj22Yu9cWwwuVg_2)(void* o);
static N_INLINE(tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ*, to__g6ziajH1gssveMp8KIs8MApy_lib)(void* p);
N_LIB_PRIVATE N_CDECL(void*, iterNext__TMTCC6fq12K15WuKEA8z4w)(void* i);
static N_INLINE(void, updateStackBottom__FRn3WNsRdbdvfuL6O7x1BQnimpy)(void);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void*, pythonException__Zl8uxcjgHaQZB15tcqXlTA)(Exception* e);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils)(void* p);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg__jLt3ACHcgYt9bbV4Vf9a5mgwsystem)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initPyModule__DD6uuT0cNlotk9a8nyu9bE7wnimpy)(tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg* p, tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m);
static N_INLINE(tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg*, to__wt9cwaSUiMGJ5i7qopVibqApy_lib)(void* p);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, GC_disable__RsY2eAkO9aEvlDhb7ZyRF8g_2system)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, GC_enable__RsY2eAkO9aEvlDhb7ZyRF8g_3system)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, pyDictHasKey__gPPk6uJ9bWMpMyW6uS9azQWg)(void* o, NCSTRING k);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___gPPk6uJ9bWMpMyW6uS9azQWg_2)(void* o, NCSTRING k);
static N_INLINE(NIM_BOOL, eqeq___aqip9cmQIuefPKdd25wuEEwsystem)(NCSTRING x, NCSTRING y);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___rh9a6aY6urF0Nohf9aeDyH4Q)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, pyObjToNimStr__eEwHrfmOllfqMcr3IQY2zQ)(void* o, NimStringDesc** v);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, pyStringToNim__9cjH8eaYe0aMdbQ9bg4rwiDw)(void* o, NimStringDesc** output);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
TNimType NTI__gBC8z6Ez5xj3dXoP0ylCRA_;
extern TNimType NTI__S9agCYBinaYZnGWcjTdxclg_;
extern TNimType NTI__9aWi1PsmvCuTKIYDHHnhfcw_;
TNimType NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_;
TNimType NTI__BKCcJxogshNojOoN23Qfbg_;
TNimType NTI__v2GijgCrTru9brL7cjgOkag_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI__eYT4U6bGFqFBUxk9b15mfOA_;
extern TNimType NTI__WC29aEeHi2Pdy9c4AkllcBTg_;
TNimType NTI__mAI4KvRAgoko9bmrV4QRgaQ_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI__1Ib9a4sxiw4YCYbDTADLEsg_;
TNimType NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_;
TNimType NTI__xxWWYOndkW9adiM61bZkvsg_;
extern tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig* pyLib__nxKBiAukGMNwnUq9bpn9adyw;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__IcYaEuuWivYAS86vFMTS3Q;
extern NU pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q;
extern TNimType NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_;
extern TNimType NTI__XEycrCsme5C8CVWAYEcdBQ_;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
extern TNimType NTI__ShBqCFAISBSH2YqBfe6zjg_;
extern TNimType NTI__G9cUlLvU4AFC26wbFxLFkFA_;
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_6, "Internal pynim error. Free called on Nim object.", 48);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_11, "nimpy.", 6);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_13, "Unexpected error encountered: ", 30);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_16, "() takes exactly ", 17);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_17, " arguments (", 12);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_18, " given)", 7);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_19, "API usage error: GC_enable called but GC is already enabled", 59);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_20, "() missing 1 required positional argument: ", 43);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_24, "() got multiple values for argument ", 36);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_28, "nimpy.nim(718, 9) `not p.isNil` ", 32);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_29, "Can\'t convert python obj of type \'$1\' to string", 47);
STRING_LITERAL(TM__LoH0foxqckmmftA2y2Dp9aw_30, "() got an unexpected keyword argument ", 38);
static N_NIMCALL(void, Marker_tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg)(void* p, NI op) {
	tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg* a;
	NI T1_;
	a = (tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence__mAI4KvRAgoko9bmrV4QRgaQ)(void* p, NI op) {
	tySequence__mAI4KvRAgoko9bmrV4QRgaQ* a;
	NI T1_;
	a = (tySequence__mAI4KvRAgoko9bmrV4QRgaQ*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence__1Ib9a4sxiw4YCYbDTADLEsg)(void* p, NI op) {
	tySequence__1Ib9a4sxiw4YCYbDTADLEsg* a;
	NI T1_;
	a = (tySequence__1Ib9a4sxiw4YCYbDTADLEsg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].fullName, op);
	nimGCvisit((void*)a->data[T1_].methods, op);
	nimGCvisit((void*)a->data[T1_].members, op);
	}
}
static N_NIMCALL(void, Marker_tySequence__xxWWYOndkW9adiM61bZkvsg)(void* p, NI op) {
	tySequence__xxWWYOndkW9adiM61bZkvsg* a;
	NI T1_;
	a = (tySequence__xxWWYOndkW9adiM61bZkvsg*)p;
	T1_ = (NI)0;
}
N_LIB_PRIVATE N_NIMCALL(void, initPythonModuleDesc__0f1AKGy9a6FMRjtYbL5nSQg)(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc) {	(*m).name = name;
	(*m).doc = doc;
}
static N_INLINE(void*, pythonLibHandleForThisProcess__qoq1L3DB9cXw9c9bTTVSl8S0gpy_lib)(void) {	void* result;
	result = (void*)0;
	result = loadLib__3W0xEugBG13TxVu4hk9b9b5g();
	return result;
}
static N_INLINE(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*, loadPyLibFromThisProcess__RtM7ZRu1XQXT9bXM8dFhSWgpy_lib)(void) {	tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig* result;
	void* T1_;
	result = (tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*)0;
	T1_ = (void*)0;
	T1_ = pythonLibHandleForThisProcess__qoq1L3DB9cXw9c9bTTVSl8S0gpy_lib();
	result = loadPyLibFromModule__bRaZxNTpbKALHcCxxa9aNCA(T1_);
	return result;
}
static N_INLINE(void, incRef__AT1eRuflKWyTTBdLjEDZbg_3system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem)(void* usr) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI) 16)))));
	return result;
}
static N_INLINE(void, rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {	addZCT__Y66tOYFjgwJ0k4aLz4bc0Q((&gch__IcYaEuuWivYAS86vFMTS3Q.zct), c);
}
static N_INLINE(void, decRef__AT1eRuflKWyTTBdLjEDZbgsystem)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {	(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	{
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT__AT1eRuflKWyTTBdLjEDZbg_2system(c);
	}
	LA3_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(src);
		incRef__AT1eRuflKWyTTBdLjEDZbg_3system(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem((*dest));
		decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, initCommon__QOPr6RYgxP9c8n2lZVbiDwA_2)(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m) {	tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw T5_;
	NI T6_;
	{
		if (!(pyLib__nxKBiAukGMNwnUq9bpn9adyw == 0)) goto LA3_;
		asgnRef((void**) (&pyLib__nxKBiAukGMNwnUq9bpn9adyw), loadPyLibFromThisProcess__RtM7ZRu1XQXT9bXM8dFhSWgpy_lib());
	}
	LA3_: ;
	nimZeroMem((void*)(&T5_), sizeof(tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw));
	unsureAsgnRef((void**) (&(*m).methods), (tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg*) incrSeqV3((TGenericSeq*)((*m).methods), (&NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_)));
	T6_ = (*m).methods->Sup.len++;
	(*m).methods->data[T6_] = T5_;
}
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void*, pyAlloc__1Aee2onoqwg9aFJWAasp3iAnimpy)(NI sz) {	void* result;
	void* T1_;
	result = (void*)0;
	T1_ = (void*)0;
	T1_ = alloc0__WrVG9abV9chlTLqkiXYLKwUg(((NI)chckRange((NU)((NU64)(((NU) (sz))) + (NU64)(pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q)), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	result = ((void*) (T1_));
	return result;
}
static N_INLINE(tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*, to__5tJl9a9cvcVqYJFbXrlgYbfApy_lib)(void* p) {	tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* result;
	result = (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*)0;
	result = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) ((NU)((NU64)(((NU) (ptrdiff_t) (p))) + (NU64)(pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q))));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, subInt)(NI a, NI b) {	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__QFQqcLB3lgOdwipkv9a60xwsystem(p);
	decRef__AT1eRuflKWyTTBdLjEDZbgsystem(T1_);
}
N_LIB_PRIVATE N_CDECL(void, freeNimObj__jz2epPJWRa0T6WbzV9cD4Og)(void* p) {	Exception* eX60gensym370882_;
	NimStringDesc* T1_;
	eX60gensym370882_ = (Exception*)0;
	eX60gensym370882_ = (Exception*) newObj((&NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_), sizeof(Exception));
	(*eX60gensym370882_).Sup.m_type = (&NTI__XEycrCsme5C8CVWAYEcdBQ_);
	(*eX60gensym370882_).name = "Exception";
	T1_ = (NimStringDesc*)0;
	T1_ = (*eX60gensym370882_).message; (*eX60gensym370882_).message = copyStringRC1(((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_6));
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*eX60gensym370882_).parent), NIM_NIL);
	raiseExceptionEx((Exception*)eX60gensym370882_, "Exception", "freeNimObj", "nimpy.nim", 204);
}
static N_INLINE(tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA*, toNim__BNt3aWEMNlje8KgYqFe8Vwnimpy)(void* p) {	tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA* result;
	result = (tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA*)0;
	result = ((tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA*) ((NU)((NU64)(((NU) (ptrdiff_t) (p))) - (NU64)(((NU) 24)))));
	return result;
}
N_LIB_PRIVATE N_CDECL(void, destructNimObj__5aiupm4TAhj22Yu9cWwwuVg)(void* o) {	tyObject_PyNimObjectcolonObjectType___EzO9cx6qeJIOpzFHShySXxA* n;
	n = toNim__BNt3aWEMNlje8KgYqFe8Vwnimpy(o);
	if (n) { nimGCunref(n); }
}
static N_INLINE(tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*, to__4gaYCHYBaCTIs6wfSrqsEApy_lib)(void* p) {	tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* result;
	result = (tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*)0;
	result = ((tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*) ((NU)((NU64)(((NU) (ptrdiff_t) (p))) + (NU64)(pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q))));
	return result;
}
static N_INLINE(NI, addInt)(NI a, NI b) {	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, incRef__CnqcscfOCAX2jCHv3dRPDwpy_utils)(void* p) {	tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* T1_;
	NI TM__LoH0foxqckmmftA2y2Dp9aw_7;
	T1_ = (tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*)0;
	T1_ = to__4gaYCHYBaCTIs6wfSrqsEApy_lib(p);
	TM__LoH0foxqckmmftA2y2Dp9aw_7 = addInt((*T1_).ob_refcnt, ((NI) 1));
	(*T1_).ob_refcnt = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_7);
}
static N_INLINE(tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ*, to__g6ziajH1gssveMp8KIs8MApy_lib)(void* p) {	tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ* result;
	result = (tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ*)0;
	result = ((tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ*) ((NU)((NU64)(((NU) (ptrdiff_t) (p))) + (NU64)(pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q))));
	return result;
}
N_LIB_PRIVATE N_CDECL(void, destructNimIterator__5aiupm4TAhj22Yu9cWwwuVg_2)(void* o) {	tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ* n;
	n = to__g6ziajH1gssveMp8KIs8MApy_lib(o);
	if ((*n).iRef) { nimGCunref((*n).iRef); }
}
static N_INLINE(void, updateStackBottom__FRn3WNsRdbdvfuL6O7x1BQnimpy)(void) {	NI volatile a;
	a = (NI)0;
	nimGC_setStackBottom(((void*) (((NU) (ptrdiff_t) ((&a))))));
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler__rqLlY5bs9atDw2OXYqJEn5g;
	excHandler__rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_INLINE(void, popSafePoint)(void) {	excHandler__rqLlY5bs9atDw2OXYqJEn5g = (*excHandler__rqLlY5bs9atDw2OXYqJEn5g).prev;
}
static N_INLINE(Exception*, getCurrentException)(void) {	Exception* result;
	result = (Exception*)0;
	result = currException__9bVPeDJlYTi9bQApZpfH8wjg;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils)(void* p) {	tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* o;
	NI TM__LoH0foxqckmmftA2y2Dp9aw_12;
	o = to__4gaYCHYBaCTIs6wfSrqsEApy_lib(p);
	TM__LoH0foxqckmmftA2y2Dp9aw_12 = subInt((*o).ob_refcnt, ((NI) 1));
	(*o).ob_refcnt = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_12);
	{
		if (!((*o).ob_refcnt == ((NI) 0))) goto LA3_;
		(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyDealloc(p);
	}
	LA3_: ;
}
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg__jLt3ACHcgYt9bbV4Vf9a5mgwsystem)(void) {	NimStringDesc* result;
	Exception* e;
{	result = (NimStringDesc*)0;
	e = getCurrentException();
	{
		if (!(e == NIM_NIL)) goto LA3_;
		result = ((NimStringDesc*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, pythonException__Zl8uxcjgHaQZB15tcqXlTA)(Exception* e) {	void* result;
	void* err;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	result = (void*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = cstrToNimstr((*e).name);
	T1_ = rawNewString((T2_ ? T2_->Sup.len : 0) + 6);
appendString(T1_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_11));
appendString(T1_, T2_);
	err = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_NewException(nimToCStringConv(T1_), (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).NimPyException, NIM_NIL);
	decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(err);
	T3_ = (NimStringDesc*)0;
	T4_ = (NimStringDesc*)0;
	T4_ = getCurrentExceptionMsg__jLt3ACHcgYt9bbV4Vf9a5mgwsystem();
	T3_ = rawNewString((T4_ ? T4_->Sup.len : 0) + 30);
appendString(T3_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_13));
appendString(T3_, T4_);
	(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_SetString(err, nimToCStringConv(T3_));
	return result;
}
static N_INLINE(void, popCurrentException)(void) {	asgnRef((void**) (&currException__9bVPeDJlYTi9bQApZpfH8wjg), (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);
}
N_LIB_PRIVATE N_CDECL(void*, iterNext__TMTCC6fq12K15WuKEA8z4w)(void* i) {	void* result;
	TSafePoint TM__LoH0foxqckmmftA2y2Dp9aw_9;
	result = (void*)0;
	updateStackBottom__FRn3WNsRdbdvfuL6O7x1BQnimpy();
	pushSafePoint(&TM__LoH0foxqckmmftA2y2Dp9aw_9);
	TM__LoH0foxqckmmftA2y2Dp9aw_9.status = _setjmp(TM__LoH0foxqckmmftA2y2Dp9aw_9.context);
	if (TM__LoH0foxqckmmftA2y2Dp9aw_9.status == 0) {
		tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ* T2_;
		T2_ = (tyObject_PyIteratorObj__GqRpYj9a7yzFP1C6hQf7QBQ*)0;
		T2_ = to__g6ziajH1gssveMp8KIs8MApy_lib(i);
		result = (*(*T2_).iRef).iter.ClP_0((*(*T2_).iRef).iter.ClE_0);
		popSafePoint();
	}
	else {
		popSafePoint();
		if (isObj(getCurrentException()->Sup.m_type, (&NTI__XEycrCsme5C8CVWAYEcdBQ_))) {
			Exception* e;
			TM__LoH0foxqckmmftA2y2Dp9aw_9.status = 0;
			e = getCurrentException();
			result = pythonException__Zl8uxcjgHaQZB15tcqXlTA(e);
			popCurrentException();
		}
	}
	if (TM__LoH0foxqckmmftA2y2Dp9aw_9.status != 0) reraiseException();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initModuleTypes__csb2z5UIH3D9cgBHISzH54g)(void* p, tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m) {	tyProc__jvPpjMAkI9bwM1B9apOphnlA selfIter;
	int T20_;
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		T2_ = ((*m).types ? (*m).types->Sup.len : 0);
		colontmp_ = T2_;
		i_2 = ((NI) 0);
		{
			while (1) {
				void* typ;
				tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* ty;
				NI TM__LoH0foxqckmmftA2y2Dp9aw_5;
				int T5_;
				int T6_;
				NI TM__LoH0foxqckmmftA2y2Dp9aw_8;
				if (!(i_2 < colontmp_)) goto LA4;
				i = i_2;
				typ = pyAlloc__1Aee2onoqwg9aFJWAasp3iAnimpy(((NI) 400));
				ty = to__5tJl9a9cvcVqYJFbXrlgYbfApy_lib(typ);
				if ((NU)(i) >= (NU)((*m).types ? (*m).types->Sup.len : 0)) raiseIndexError2(i,((*m).types ? (*m).types->Sup.len : 0)-1);
				(*ty).tp_name = nimToCStringConv((*m).types->data[i].fullName);
				if ((NU)(i) >= (NU)((*m).types ? (*m).types->Sup.len : 0)) raiseIndexError2(i,((*m).types ? (*m).types->Sup.len : 0)-1);
				TM__LoH0foxqckmmftA2y2Dp9aw_5 = subInt(((int)chckRange((*m).types->data[i].origSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 8));
				if (TM__LoH0foxqckmmftA2y2Dp9aw_5 < (-2147483647 -1) || TM__LoH0foxqckmmftA2y2Dp9aw_5 > 2147483647) raiseOverflow();
				(*ty).tp_basicsize = ((NI) ((NI32)(TM__LoH0foxqckmmftA2y2Dp9aw_5)));
				(*ty).tp_flags = ((unsigned long) 131563);
				if ((NU)(i) >= (NU)((*m).types ? (*m).types->Sup.len : 0)) raiseIndexError2(i,((*m).types ? (*m).types->Sup.len : 0)-1);
				(*ty).tp_doc = (*m).types->data[i].doc;
				if ((NU)(i) >= (NU)((*m).types ? (*m).types->Sup.len : 0)) raiseIndexError2(i,((*m).types ? (*m).types->Sup.len : 0)-1);
				(*ty).tp_new = (*m).types->data[i].newFunc;
				(*ty).tp_free = freeNimObj__jz2epPJWRa0T6WbzV9cD4Og;
				(*ty).tp_dealloc = destructNimObj__5aiupm4TAhj22Yu9cWwwuVg;
				T5_ = (int)0;
				T5_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyType_Ready(((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (typ)));
				(void)(T5_);
				incRef__CnqcscfOCAX2jCHv3dRPDwpy_utils(typ);
				if ((NU)(i) >= (NU)((*m).types ? (*m).types->Sup.len : 0)) raiseIndexError2(i,((*m).types ? (*m).types->Sup.len : 0)-1);
				T6_ = (int)0;
				T6_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyModule_AddObject(p, (*m).types->data[i].name, typ);
				(void)(T6_);
				TM__LoH0foxqckmmftA2y2Dp9aw_8 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_8);
			} LA4: ;
		}
	}
	{
		NI T9_;
		void* T12_;
		T9_ = ((*m).iterators ? (*m).iterators->Sup.len : 0);
		if (!!((T9_ == ((NI) 0)))) goto LA10_;
		T12_ = (void*)0;
		T12_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).module, "PyObject_SelfIter");
		selfIter = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T12_));
	}
	goto LA7_;
	LA10_: ;
	{
		selfIter = NIM_NIL;
	}
	LA7_: ;
	{
		NI i_3;
		NI colontmp__2;
		NI T15_;
		NI i_4;
		i_3 = (NI)0;
		colontmp__2 = (NI)0;
		T15_ = ((*m).iterators ? (*m).iterators->Sup.len : 0);
		colontmp__2 = T15_;
		i_4 = ((NI) 0);
		{
			while (1) {
				void* typ_2;
				tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* ty_2;
				int T18_;
				int T19_;
				NI TM__LoH0foxqckmmftA2y2Dp9aw_14;
				if (!(i_4 < colontmp__2)) goto LA17;
				i_3 = i_4;
				typ_2 = pyAlloc__1Aee2onoqwg9aFJWAasp3iAnimpy(((NI) 400));
				ty_2 = to__5tJl9a9cvcVqYJFbXrlgYbfApy_lib(typ_2);
				if ((NU)(i_3) >= (NU)((*m).iterators ? (*m).iterators->Sup.len : 0)) raiseIndexError2(i_3,((*m).iterators ? (*m).iterators->Sup.len : 0)-1);
				(*ty_2).tp_name = (*m).iterators->data[i_3].name;
				(*ty_2).tp_basicsize = ((NI) 32);
				(*ty_2).tp_flags = ((unsigned long) 131563);
				if ((NU)(i_3) >= (NU)((*m).iterators ? (*m).iterators->Sup.len : 0)) raiseIndexError2(i_3,((*m).iterators ? (*m).iterators->Sup.len : 0)-1);
				(*ty_2).tp_doc = (*m).iterators->data[i_3].doc;
				if ((NU)(i_3) >= (NU)((*m).iterators ? (*m).iterators->Sup.len : 0)) raiseIndexError2(i_3,((*m).iterators ? (*m).iterators->Sup.len : 0)-1);
				(*ty_2).tp_new = (*m).iterators->data[i_3].newFunc;
				(*ty_2).tp_free = freeNimObj__jz2epPJWRa0T6WbzV9cD4Og;
				(*ty_2).tp_dealloc = destructNimIterator__5aiupm4TAhj22Yu9cWwwuVg_2;
				(*ty_2).tp_iternext = iterNext__TMTCC6fq12K15WuKEA8z4w;
				(*ty_2).tp_iter = selfIter;
				T18_ = (int)0;
				T18_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyType_Ready(((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (typ_2)));
				(void)(T18_);
				incRef__CnqcscfOCAX2jCHv3dRPDwpy_utils(typ_2);
				if ((NU)(i_3) >= (NU)((*m).iterators ? (*m).iterators->Sup.len : 0)) raiseIndexError2(i_3,((*m).iterators ? (*m).iterators->Sup.len : 0)-1);
				T19_ = (int)0;
				T19_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyModule_AddObject(p, (*m).iterators->data[i_3].name, typ_2);
				(void)(T19_);
				TM__LoH0foxqckmmftA2y2Dp9aw_14 = addInt(i_4, ((NI) 1));
				i_4 = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_14);
			} LA17: ;
		}
	}
	(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).NimPyException = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_NewException("nimpy.NimPyException", NIM_NIL, NIM_NIL);
	T20_ = (int)0;
	T20_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyModule_AddObject(p, "NimPyException", (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).NimPyException);
	(void)(T20_);
}
N_LIB_PRIVATE N_NIMCALL(void, initModule2__QOPr6RYgxP9c8n2lZVbiDwA)(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m) {	tyProc__2ujOETN3z9btuXStkbh8Cdg Py_InitModule4;
	void* T1_;
	initCommon__QOPr6RYgxP9c8n2lZVbiDwA_2(m);
	Py_InitModule4 = (tyProc__2ujOETN3z9btuXStkbh8Cdg)0;
	T1_ = (void*)0;
	T1_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).module, "Py_InitModule4");
	Py_InitModule4 = ((tyProc__2ujOETN3z9btuXStkbh8Cdg) (T1_));
	{
		void* T6_;
		if (!(Py_InitModule4 == 0)) goto LA4_;
		T6_ = (void*)0;
		T6_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).module, "Py_InitModule4_64");
		Py_InitModule4 = ((tyProc__2ujOETN3z9btuXStkbh8Cdg) (T6_));
	}
	LA4_: ;
	{
		void* py;
		if (!!((Py_InitModule4 == 0))) goto LA9_;
		if ((NU)(((NI) 0)) >= (NU)((*m).methods ? (*m).methods->Sup.len : 0)) raiseIndexError2(((NI) 0),((*m).methods ? (*m).methods->Sup.len : 0)-1);
		py = Py_InitModule4((*m).name, (&(*m).methods->data[((NI) 0)]), (*m).doc, NIM_NIL, ((int) 1013));
		initModuleTypes__csb2z5UIH3D9cgBHISzH54g(py, (&(*m)));
	}
	LA9_: ;
}
static N_INLINE(void, initPyModule__DD6uuT0cNlotk9a8nyu9bE7wnimpy)(tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg* p, tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m) {	(*p).m_base.ob_base.ob_refcnt = ((NI) 1);
	(*p).m_name = (*m).name;
	(*p).m_doc = (*m).doc;
	(*p).m_size = ((NI) -1);
	if ((NU)(((NI) 0)) >= (NU)((*m).methods ? (*m).methods->Sup.len : 0)) raiseIndexError2(((NI) 0),((*m).methods ? (*m).methods->Sup.len : 0)-1);
	(*p).m_methods = (&(*m).methods->data[((NI) 0)]);
}
static N_INLINE(tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg*, to__wt9cwaSUiMGJ5i7qopVibqApy_lib)(void* p) {	tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg* result;
	result = (tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg*)0;
	result = ((tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg*) ((NU)((NU64)(((NU) (ptrdiff_t) (p))) + (NU64)(pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, initModule3__b5gVEAN0cbSksVFIpPmViA)(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m) {	void* result;
	tyProc__BEMKLd49c5qNHqmldA6aVaw PyModule_Create2;
	void* T1_;
	result = (void*)0;
	initCommon__QOPr6RYgxP9c8n2lZVbiDwA_2(m);
	PyModule_Create2 = (tyProc__BEMKLd49c5qNHqmldA6aVaw)0;
	T1_ = (void*)0;
	T1_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).module, "PyModule_Create2");
	PyModule_Create2 = ((tyProc__BEMKLd49c5qNHqmldA6aVaw) (T1_));
	{
		void* T6_;
		if (!(PyModule_Create2 == 0)) goto LA4_;
		T6_ = (void*)0;
		T6_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).module, "PyModule_Create2TraceRefs");
		PyModule_Create2 = ((tyProc__BEMKLd49c5qNHqmldA6aVaw) (T6_));
	}
	LA4_: ;
	{
		void* pymod;
		tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg* T11_;
		if (!!((PyModule_Create2 == 0))) goto LA9_;
		pymod = pyAlloc__1Aee2onoqwg9aFJWAasp3iAnimpy(((NI) 104));
		T11_ = (tyObject_PyModuleDef__QZDAPlXtpUM7Y9asxNBUBwg*)0;
		T11_ = to__wt9cwaSUiMGJ5i7qopVibqApy_lib(pymod);
		initPyModule__DD6uuT0cNlotk9a8nyu9bE7wnimpy(T11_, m);
		result = PyModule_Create2(pymod, ((int) 3));
		initModuleTypes__csb2z5UIH3D9cgBHISzH54g(result, (&(*m)));
	}
	LA9_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, addMethod__TpUnmhxGlZgxTBTLPiE3nw)(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA* m, NCSTRING name, NCSTRING doc, tyProc__uQWqJp3WAx8fOY1h9aCwjIg f) {	tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw def;
	NI T1_;
	chckNil((void*)(&def));
	nimZeroMem((void*)(&def), sizeof(tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw));
	def.ml_name = name;
	def.ml_meth = f;
	def.ml_flags = ((int) 3);
	def.ml_doc = doc;
	unsureAsgnRef((void**) (&(*m).methods), (tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg*) incrSeqV3((TGenericSeq*)((*m).methods), (&NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_)));
	T1_ = (*m).methods->Sup.len++;
	(*m).methods->data[T1_] = def;
}
static N_INLINE(void, GC_disable__RsY2eAkO9aEvlDhb7ZyRF8g_2system)(void) {	gch__IcYaEuuWivYAS86vFMTS3Q.recGcLock += ((NI) 1);
}
static N_INLINE(void, GC_enable__RsY2eAkO9aEvlDhb7ZyRF8g_3system)(void) {	{
		tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA* eX60gensym99626_;
		NimStringDesc* T5_;
		if (!(gch__IcYaEuuWivYAS86vFMTS3Q.recGcLock <= ((NI) 0))) goto LA3_;
		eX60gensym99626_ = (tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA*)0;
		eX60gensym99626_ = (tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA*) newObj((&NTI__ShBqCFAISBSH2YqBfe6zjg_), sizeof(tyObject_AssertionError__G9cUlLvU4AFC26wbFxLFkFA));
		(*eX60gensym99626_).Sup.Sup.Sup.m_type = (&NTI__G9cUlLvU4AFC26wbFxLFkFA_);
		(*eX60gensym99626_).Sup.Sup.name = "AssertionError";
		T5_ = (NimStringDesc*)0;
		T5_ = (*eX60gensym99626_).Sup.Sup.message; (*eX60gensym99626_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_19));
		if (T5_) nimGCunrefNoCycle(T5_);
		asgnRef((void**) (&(*eX60gensym99626_).Sup.Sup.parent), NIM_NIL);
		raiseExceptionEx((Exception*)eX60gensym99626_, "AssertionError", "GC_enable", "gc.nim", 834);
	}
	LA3_: ;
	gch__IcYaEuuWivYAS86vFMTS3Q.recGcLock -= ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, pyDictHasKey__gPPk6uJ9bWMpMyW6uS9azQWg)(void* o, NCSTRING k) {	NIM_BOOL result;
	void* pk;
	int T1_;
	result = (NIM_BOOL)0;
	pk = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyUnicode_FromString(k);
	T1_ = (int)0;
	T1_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyDict_Contains(o, pk);
	result = (T1_ == ((NI32) 1));
	decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(pk);
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___aqip9cmQIuefPKdd25wuEEwsystem)(NCSTRING x, NCSTRING y) {	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___gPPk6uJ9bWMpMyW6uS9azQWg_2)(void* o, NCSTRING k) {	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NCSTRING T5_;
		if (!((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyUnicode_CompareWithASCIIString == 0)) goto LA3_;
		T5_ = (NCSTRING)0;
		T5_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyString_AsString(o);
		result = eqeq___aqip9cmQIuefPKdd25wuEEwsystem(T5_, k);
	}
	goto LA1_;
	LA3_: ;
	{
		int T7_;
		T7_ = (int)0;
		T7_ = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyUnicode_CompareWithASCIIString(o, k);
		result = (T7_ == ((NI32) 0));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, pyObjToNimStr__eEwHrfmOllfqMcr3IQY2zQ)(void* o, NimStringDesc** v) {	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* typ;
		NimStringDesc* errString;
		Exception* eX60gensym372609_;
		tyArray__nHXaesL0DJZHyVS07ARPRA T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = pyStringToNim__9cjH8eaYe0aMdbQ9bg4rwiDw(o, v);
		T4_ = (NIM_BOOL)0;
		T4_ = NIM_UNLIKELY(!(T3_));
		if (!T4_) goto LA5_;
		typ = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) ((*((tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*) (o))).ob_type));
		errString = copyString(((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_29));
		eX60gensym372609_ = (Exception*)0;
		eX60gensym372609_ = (Exception*) newObj((&NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_), sizeof(Exception));
		(*eX60gensym372609_).Sup.m_type = (&NTI__XEycrCsme5C8CVWAYEcdBQ_);
		(*eX60gensym372609_).name = "Exception";
		nimZeroMem((void*)T7_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T7_[0] = cstrToNimstr((*typ).tp_name);
		asgnRef((void**) (&(*eX60gensym372609_).message), nsuFormatOpenArray(errString, T7_, 1));
		asgnRef((void**) (&(*eX60gensym372609_).parent), NIM_NIL);
		raiseExceptionEx((Exception*)eX60gensym372609_, "Exception", "pyObjToNimStr", "nimpy.nim", 367);
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___rh9a6aY6urF0Nohf9aeDyH4Q)(void* p) {	NimStringDesc* result;
	void* s;
	result = (NimStringDesc*)0;
	{
		if (!!(!((p == 0)))) goto LA3_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_28));
	}
	LA3_: ;
	s = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyObject_Str(p);
	pyObjToNimStr__eEwHrfmOllfqMcr3IQY2zQ(s, (&result));
	decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(s);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, verifyArgs__8sVYJT4zfbIXMNXtJ2cTng)(void* argTuple, void* kwargsDict, NI argsLen, NI argsLenReq, NCSTRING* argNames, NI argNamesLen_0, NimStringDesc* funcName) {	NIM_BOOL result;
	NI nargs;
	NI nkwargs;
	NI sz;
	NI TM__LoH0foxqckmmftA2y2Dp9aw_15;
	NI nkwarg_left;
{	result = (NIM_BOOL)0;
	{
		if (!(argTuple == 0)) goto LA3_;
		nargs = ((NI) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		nargs = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyTuple_Size(argTuple);
	}
	LA1_: ;
	{
		if (!(kwargsDict == 0)) goto LA8_;
		nkwargs = ((NI) 0);
	}
	goto LA6_;
	LA8_: ;
	{
		nkwargs = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyDict_Size(kwargsDict);
	}
	LA6_: ;
	TM__LoH0foxqckmmftA2y2Dp9aw_15 = addInt(nargs, nkwargs);
	sz = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_15);
	nkwarg_left = nkwargs;
	{
		NIM_BOOL T15_;
		if (!(argsLenReq < argsLen)) goto LA13_;
		T15_ = (NIM_BOOL)0;
		T15_ = (argsLenReq <= sz);
		if (!(T15_)) goto LA16_;
		T15_ = (sz <= argsLen);
		LA16_: ;
		result = T15_;
	}
	goto LA11_;
	LA13_: ;
	{
		result = (sz == argsLen);
	}
	LA11_: ;
	{
		NimStringDesc* T22_;
		NimStringDesc* T23_;
		NimStringDesc* T24_;
		if (!!(result)) goto LA20_;
		GC_disable__RsY2eAkO9aEvlDhb7ZyRF8g_2system();
		T22_ = (NimStringDesc*)0;
		T23_ = (NimStringDesc*)0;
		T23_ = nimIntToStr(argsLen);
		T24_ = (NimStringDesc*)0;
		T24_ = nimIntToStr(sz);
		T22_ = rawNewString((funcName ? funcName->Sup.len : 0) + (T23_ ? T23_->Sup.len : 0) + (T24_ ? T24_->Sup.len : 0) + 36);
appendString(T22_, funcName);
appendString(T22_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_16));
appendString(T22_, T23_);
appendString(T22_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_17));
appendString(T22_, T24_);
appendString(T22_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_18));
		(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_SetString((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyExc_TypeError, nimToCStringConv(T22_));
		GC_enable__RsY2eAkO9aEvlDhb7ZyRF8g_3system();
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA20_: ;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__LoH0foxqckmmftA2y2Dp9aw_23;
				if (!(i_2 < sz)) goto LA27;
				i = i_2;
				{
					{
						if (!(i < nargs)) goto LA31_;
						goto LA28;
					}
					goto LA29_;
					LA31_: ;
					{
						NIM_BOOL T34_;
						T34_ = (NIM_BOOL)0;
						T34_ = (i < argsLenReq);
						if (!(T34_)) goto LA35_;
						T34_ = (((NI) 0) < nkwargs);
						LA35_: ;
						if (!T34_) goto LA36_;
						{
							NIM_BOOL T40_;
							NimStringDesc* T43_;
							NimStringDesc* T44_;
							if ((NU)(i) >= (NU)(argNamesLen_0)) raiseIndexError2(i,argNamesLen_0-1);
							T40_ = (NIM_BOOL)0;
							T40_ = pyDictHasKey__gPPk6uJ9bWMpMyW6uS9azQWg(kwargsDict, argNames[i]);
							if (!!(T40_)) goto LA41_;
							GC_disable__RsY2eAkO9aEvlDhb7ZyRF8g_2system();
							T43_ = (NimStringDesc*)0;
							if ((NU)(i) >= (NU)(argNamesLen_0)) raiseIndexError2(i,argNamesLen_0-1);
							T44_ = (NimStringDesc*)0;
							T44_ = cstrToNimstr(argNames[i]);
							T43_ = rawNewString((funcName ? funcName->Sup.len : 0) + (T44_ ? T44_->Sup.len : 0) + 43);
appendString(T43_, funcName);
appendString(T43_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_20));
appendString(T43_, T44_);
							(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_SetString((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyExc_TypeError, nimToCStringConv(T43_));
							GC_enable__RsY2eAkO9aEvlDhb7ZyRF8g_3system();
							result = NIM_FALSE;
							goto BeforeRet_;
						}
						goto LA38_;
						LA41_: ;
						{
							NI TM__LoH0foxqckmmftA2y2Dp9aw_21;
							TM__LoH0foxqckmmftA2y2Dp9aw_21 = subInt(nkwarg_left, ((NI) 1));
							nkwarg_left = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_21);
						}
						LA38_: ;
					}
					goto LA29_;
					LA36_: ;
					{
						if (!(((NI) 0) < nkwargs)) goto LA47_;
						{
							NIM_BOOL T51_;
							NI TM__LoH0foxqckmmftA2y2Dp9aw_22;
							if ((NU)(i) >= (NU)(argNamesLen_0)) raiseIndexError2(i,argNamesLen_0-1);
							T51_ = (NIM_BOOL)0;
							T51_ = pyDictHasKey__gPPk6uJ9bWMpMyW6uS9azQWg(kwargsDict, argNames[i]);
							if (!T51_) goto LA52_;
							TM__LoH0foxqckmmftA2y2Dp9aw_22 = subInt(nkwarg_left, ((NI) 1));
							nkwarg_left = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_22);
						}
						LA52_: ;
					}
					goto LA29_;
					LA47_: ;
					LA29_: ;
				} LA28: ;
				TM__LoH0foxqckmmftA2y2Dp9aw_23 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_23);
			} LA27: ;
		}
	}
	{
		if (!(((NI) 0) < nkwarg_left)) goto LA56_;
		{
			if (!(((NI) 0) < nargs)) goto LA60_;
			{
				NI i_3;
				NI res;
				i_3 = (NI)0;
				res = ((NI) 0);
				{
					while (1) {
						NI TM__LoH0foxqckmmftA2y2Dp9aw_25;
						if (!(res <= nargs)) goto LA64;
						i_3 = res;
						{
							NIM_BOOL T67_;
							NimStringDesc* T70_;
							NimStringDesc* T71_;
							if ((NU)(i_3) >= (NU)(argNamesLen_0)) raiseIndexError2(i_3,argNamesLen_0-1);
							T67_ = (NIM_BOOL)0;
							T67_ = pyDictHasKey__gPPk6uJ9bWMpMyW6uS9azQWg(kwargsDict, argNames[i_3]);
							if (!T67_) goto LA68_;
							GC_disable__RsY2eAkO9aEvlDhb7ZyRF8g_2system();
							T70_ = (NimStringDesc*)0;
							if ((NU)(i_3) >= (NU)(argNamesLen_0)) raiseIndexError2(i_3,argNamesLen_0-1);
							T71_ = (NimStringDesc*)0;
							T71_ = cstrToNimstr(argNames[i_3]);
							T70_ = rawNewString((funcName ? funcName->Sup.len : 0) + (T71_ ? T71_->Sup.len : 0) + 36);
appendString(T70_, funcName);
appendString(T70_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_24));
appendString(T70_, T71_);
							(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_SetString((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyExc_TypeError, nimToCStringConv(T70_));
							GC_enable__RsY2eAkO9aEvlDhb7ZyRF8g_3system();
							result = NIM_FALSE;
							goto BeforeRet_;
						}
						LA68_: ;
						TM__LoH0foxqckmmftA2y2Dp9aw_25 = addInt(res, ((NI) 1));
						res = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_25);
					} LA64: ;
				}
			}
		}
		LA60_: ;
		{
			void* k;
			void* it;
			TSafePoint TM__LoH0foxqckmmftA2y2Dp9aw_26;
			k = (void*)0;
			it = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyObject_GetIter(kwargsDict);
			pushSafePoint(&TM__LoH0foxqckmmftA2y2Dp9aw_26);
			TM__LoH0foxqckmmftA2y2Dp9aw_26.status = _setjmp(TM__LoH0foxqckmmftA2y2Dp9aw_26.context);
			if (TM__LoH0foxqckmmftA2y2Dp9aw_26.status == 0) {
				{
					while (1) {
						void* i_4;
						NIM_BOOL found;
						i_4 = (*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyIter_Next(it);
						{
							if (!(i_4 == 0)) goto LA78_;
							goto LA74;
						}
						LA78_: ;
						k = i_4;
						found = NIM_FALSE;
						{
							NCSTRING a;
							NI i_5;
							a = (NCSTRING)0;
							i_5 = ((NI) 0);
							{
								while (1) {
									NI TM__LoH0foxqckmmftA2y2Dp9aw_27;
									if (!(i_5 < argNamesLen_0)) goto LA82;
									if ((NU)(i_5) >= (NU)(argNamesLen_0)) raiseIndexError2(i_5,argNamesLen_0-1);
									a = argNames[i_5];
									{
										NIM_BOOL T85_;
										T85_ = (NIM_BOOL)0;
										T85_ = eqeq___gPPk6uJ9bWMpMyW6uS9azQWg_2(k, a);
										if (!T85_) goto LA86_;
										found = NIM_TRUE;
										goto LA80;
									}
									LA86_: ;
									TM__LoH0foxqckmmftA2y2Dp9aw_27 = addInt(i_5, ((NI) 1));
									i_5 = (NI)(TM__LoH0foxqckmmftA2y2Dp9aw_27);
								} LA82: ;
							}
						} LA80: ;
						{
							NIM_BOOL T90_;
							T90_ = (NIM_BOOL)0;
							T90_ = NIM_LIKELY(found);
							if (!T90_) goto LA91_;
							decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(k);
						}
						goto LA88_;
						LA91_: ;
						{
							NimStringDesc* kStr;
							NimStringDesc* T94_;
							kStr = dollar___rh9a6aY6urF0Nohf9aeDyH4Q(k);
							decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(k);
							GC_disable__RsY2eAkO9aEvlDhb7ZyRF8g_2system();
							T94_ = (NimStringDesc*)0;
							T94_ = rawNewString((funcName ? funcName->Sup.len : 0) + (kStr ? kStr->Sup.len : 0) + 38);
appendString(T94_, funcName);
appendString(T94_, ((NimStringDesc*) &TM__LoH0foxqckmmftA2y2Dp9aw_30));
appendString(T94_, kStr);
							(*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyErr_SetString((*pyLib__nxKBiAukGMNwnUq9bpn9adyw).PyExc_TypeError, nimToCStringConv(T94_));
							GC_enable__RsY2eAkO9aEvlDhb7ZyRF8g_3system();
							result = NIM_FALSE;
							popSafePoint();
							decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(it);
							goto BeforeRet_;
						}
						LA88_: ;
					}
				} LA74: ;
				popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				decRef__CnqcscfOCAX2jCHv3dRPDw_2py_utils(it);
			}
			if (TM__LoH0foxqckmmftA2y2Dp9aw_26.status != 0) reraiseException();
		}
	}
	LA56_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimpy_nimpyDatInit000)(void) {
static TNimNode* TM__LoH0foxqckmmftA2y2Dp9aw_2_5[5];
static TNimNode* TM__LoH0foxqckmmftA2y2Dp9aw_3_8[8];
static TNimNode* TM__LoH0foxqckmmftA2y2Dp9aw_4_3[3];
static TNimNode TM__LoH0foxqckmmftA2y2Dp9aw_0[19];
NTI__gBC8z6Ez5xj3dXoP0ylCRA_.size = sizeof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA);
NTI__gBC8z6Ez5xj3dXoP0ylCRA_.kind = 18;
NTI__gBC8z6Ez5xj3dXoP0ylCRA_.base = 0;
NTI__gBC8z6Ez5xj3dXoP0ylCRA_.flags = 2;
TM__LoH0foxqckmmftA2y2Dp9aw_2_5[0] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[1];
TM__LoH0foxqckmmftA2y2Dp9aw_0[1].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[1].offset = offsetof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA, name);
TM__LoH0foxqckmmftA2y2Dp9aw_0[1].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[1].name = "name";
TM__LoH0foxqckmmftA2y2Dp9aw_2_5[1] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[2];
TM__LoH0foxqckmmftA2y2Dp9aw_0[2].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[2].offset = offsetof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA, doc);
TM__LoH0foxqckmmftA2y2Dp9aw_0[2].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[2].name = "doc";
TM__LoH0foxqckmmftA2y2Dp9aw_2_5[2] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[3];
NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_.size = sizeof(tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg*);
NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_.kind = 24;
NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_.base = (&NTI__9aWi1PsmvCuTKIYDHHnhfcw_);
NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_.flags = 2;
NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_.marker = Marker_tySequence__E2XyP5e7Jr9aMpJMjdz5Tkg;
TM__LoH0foxqckmmftA2y2Dp9aw_0[3].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[3].offset = offsetof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA, methods);
TM__LoH0foxqckmmftA2y2Dp9aw_0[3].typ = (&NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[3].name = "methods";
TM__LoH0foxqckmmftA2y2Dp9aw_2_5[3] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[4];
NTI__BKCcJxogshNojOoN23Qfbg_.size = sizeof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg);
NTI__BKCcJxogshNojOoN23Qfbg_.kind = 18;
NTI__BKCcJxogshNojOoN23Qfbg_.base = 0;
NTI__BKCcJxogshNojOoN23Qfbg_.flags = 2;
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[0] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[6];
NTI__v2GijgCrTru9brL7cjgOkag_.size = sizeof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA*);
NTI__v2GijgCrTru9brL7cjgOkag_.kind = 21;
NTI__v2GijgCrTru9brL7cjgOkag_.base = (&NTI__gBC8z6Ez5xj3dXoP0ylCRA_);
NTI__v2GijgCrTru9brL7cjgOkag_.flags = 3;
TM__LoH0foxqckmmftA2y2Dp9aw_0[6].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[6].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, module);
TM__LoH0foxqckmmftA2y2Dp9aw_0[6].typ = (&NTI__v2GijgCrTru9brL7cjgOkag_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[6].name = "module";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[1] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[7];
TM__LoH0foxqckmmftA2y2Dp9aw_0[7].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[7].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, name);
TM__LoH0foxqckmmftA2y2Dp9aw_0[7].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[7].name = "name";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[2] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[8];
TM__LoH0foxqckmmftA2y2Dp9aw_0[8].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[8].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, doc);
TM__LoH0foxqckmmftA2y2Dp9aw_0[8].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[8].name = "doc";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[3] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[9];
TM__LoH0foxqckmmftA2y2Dp9aw_0[9].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[9].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, fullName);
TM__LoH0foxqckmmftA2y2Dp9aw_0[9].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[9].name = "fullName";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[4] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[10];
TM__LoH0foxqckmmftA2y2Dp9aw_0[10].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[10].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, newFunc);
TM__LoH0foxqckmmftA2y2Dp9aw_0[10].typ = (&NTI__eYT4U6bGFqFBUxk9b15mfOA_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[10].name = "newFunc";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[5] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[11];
TM__LoH0foxqckmmftA2y2Dp9aw_0[11].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[11].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, methods);
TM__LoH0foxqckmmftA2y2Dp9aw_0[11].typ = (&NTI__E2XyP5e7Jr9aMpJMjdz5Tkg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[11].name = "methods";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[6] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[12];
NTI__mAI4KvRAgoko9bmrV4QRgaQ_.size = sizeof(tySequence__mAI4KvRAgoko9bmrV4QRgaQ*);
NTI__mAI4KvRAgoko9bmrV4QRgaQ_.kind = 24;
NTI__mAI4KvRAgoko9bmrV4QRgaQ_.base = (&NTI__WC29aEeHi2Pdy9c4AkllcBTg_);
NTI__mAI4KvRAgoko9bmrV4QRgaQ_.flags = 2;
NTI__mAI4KvRAgoko9bmrV4QRgaQ_.marker = Marker_tySequence__mAI4KvRAgoko9bmrV4QRgaQ;
TM__LoH0foxqckmmftA2y2Dp9aw_0[12].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[12].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, members);
TM__LoH0foxqckmmftA2y2Dp9aw_0[12].typ = (&NTI__mAI4KvRAgoko9bmrV4QRgaQ_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[12].name = "members";
TM__LoH0foxqckmmftA2y2Dp9aw_3_8[7] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[13];
TM__LoH0foxqckmmftA2y2Dp9aw_0[13].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[13].offset = offsetof(tyObject_PyTypeDesc__BKCcJxogshNojOoN23Qfbg, origSize);
TM__LoH0foxqckmmftA2y2Dp9aw_0[13].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[13].name = "origSize";
TM__LoH0foxqckmmftA2y2Dp9aw_0[5].len = 8; TM__LoH0foxqckmmftA2y2Dp9aw_0[5].kind = 2; TM__LoH0foxqckmmftA2y2Dp9aw_0[5].sons = &TM__LoH0foxqckmmftA2y2Dp9aw_3_8[0];
NTI__BKCcJxogshNojOoN23Qfbg_.node = &TM__LoH0foxqckmmftA2y2Dp9aw_0[5];
NTI__1Ib9a4sxiw4YCYbDTADLEsg_.size = sizeof(tySequence__1Ib9a4sxiw4YCYbDTADLEsg*);
NTI__1Ib9a4sxiw4YCYbDTADLEsg_.kind = 24;
NTI__1Ib9a4sxiw4YCYbDTADLEsg_.base = (&NTI__BKCcJxogshNojOoN23Qfbg_);
NTI__1Ib9a4sxiw4YCYbDTADLEsg_.flags = 2;
NTI__1Ib9a4sxiw4YCYbDTADLEsg_.marker = Marker_tySequence__1Ib9a4sxiw4YCYbDTADLEsg;
TM__LoH0foxqckmmftA2y2Dp9aw_0[4].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[4].offset = offsetof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA, types);
TM__LoH0foxqckmmftA2y2Dp9aw_0[4].typ = (&NTI__1Ib9a4sxiw4YCYbDTADLEsg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[4].name = "types";
TM__LoH0foxqckmmftA2y2Dp9aw_2_5[4] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[14];
NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_.size = sizeof(tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw);
NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_.kind = 18;
NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_.base = 0;
NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_.flags = 3;
TM__LoH0foxqckmmftA2y2Dp9aw_4_3[0] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[16];
TM__LoH0foxqckmmftA2y2Dp9aw_0[16].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[16].offset = offsetof(tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw, name);
TM__LoH0foxqckmmftA2y2Dp9aw_0[16].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[16].name = "name";
TM__LoH0foxqckmmftA2y2Dp9aw_4_3[1] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[17];
TM__LoH0foxqckmmftA2y2Dp9aw_0[17].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[17].offset = offsetof(tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw, doc);
TM__LoH0foxqckmmftA2y2Dp9aw_0[17].typ = (&NTI__S9agCYBinaYZnGWcjTdxclg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[17].name = "doc";
TM__LoH0foxqckmmftA2y2Dp9aw_4_3[2] = &TM__LoH0foxqckmmftA2y2Dp9aw_0[18];
TM__LoH0foxqckmmftA2y2Dp9aw_0[18].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[18].offset = offsetof(tyObject_PyIteratorDesc__3Lh9c29bpC2Iomkl9cQO9cGqEw, newFunc);
TM__LoH0foxqckmmftA2y2Dp9aw_0[18].typ = (&NTI__eYT4U6bGFqFBUxk9b15mfOA_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[18].name = "newFunc";
TM__LoH0foxqckmmftA2y2Dp9aw_0[15].len = 3; TM__LoH0foxqckmmftA2y2Dp9aw_0[15].kind = 2; TM__LoH0foxqckmmftA2y2Dp9aw_0[15].sons = &TM__LoH0foxqckmmftA2y2Dp9aw_4_3[0];
NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_.node = &TM__LoH0foxqckmmftA2y2Dp9aw_0[15];
NTI__xxWWYOndkW9adiM61bZkvsg_.size = sizeof(tySequence__xxWWYOndkW9adiM61bZkvsg*);
NTI__xxWWYOndkW9adiM61bZkvsg_.kind = 24;
NTI__xxWWYOndkW9adiM61bZkvsg_.base = (&NTI__3Lh9c29bpC2Iomkl9cQO9cGqEw_);
NTI__xxWWYOndkW9adiM61bZkvsg_.flags = 2;
NTI__xxWWYOndkW9adiM61bZkvsg_.marker = Marker_tySequence__xxWWYOndkW9adiM61bZkvsg;
TM__LoH0foxqckmmftA2y2Dp9aw_0[14].kind = 1;
TM__LoH0foxqckmmftA2y2Dp9aw_0[14].offset = offsetof(tyObject_PyModuleDesc__gBC8z6Ez5xj3dXoP0ylCRA, iterators);
TM__LoH0foxqckmmftA2y2Dp9aw_0[14].typ = (&NTI__xxWWYOndkW9adiM61bZkvsg_);
TM__LoH0foxqckmmftA2y2Dp9aw_0[14].name = "iterators";
TM__LoH0foxqckmmftA2y2Dp9aw_0[0].len = 5; TM__LoH0foxqckmmftA2y2Dp9aw_0[0].kind = 2; TM__LoH0foxqckmmftA2y2Dp9aw_0[0].sons = &TM__LoH0foxqckmmftA2y2Dp9aw_2_5[0];
NTI__gBC8z6Ez5xj3dXoP0ylCRA_.node = &TM__LoH0foxqckmmftA2y2Dp9aw_0[0];
}

