/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig;
typedef struct tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g;
typedef struct tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w;
typedef struct tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA;
typedef struct tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__M73GJ9bOx1XdoIRnhIyhqTQ tySequence__M73GJ9bOx1XdoIRnhIyhqTQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A;
typedef struct NimStringDesc NimStringDesc;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw;
typedef struct tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg;
typedef struct tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef N_CDECL_PTR(void*, tyProc__SsjMo29bx9bP5kwe2xgM3Scg) (NCSTRING f, ...);
typedef N_CDECL_PTR(void*, tyProc__4wJmT85lsn175X0dPNQv7w) (NI sz);
typedef N_CDECL_PTR(NI, tyProc__YRQqZC12s3573tRGP8MV3g) (void* f);
typedef N_CDECL_PTR(void*, tyProc__oPIasAghCTvCKmvkMeB1xQ) (void* f, NI i);
typedef N_CDECL_PTR(int, tyProc__6slETyyIDJuDOSqkO0hUXA) (void* f, NI i, void* v);
typedef N_CDECL_PTR(int, tyProc__tgpXIILGoVcO9bvYnz9azTVQ) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* f);
typedef N_CDECL_PTR(void*, tyProc__eYT4U6bGFqFBUxk9b15mfOA) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* f, void* a, void* b);
typedef N_CDECL_PTR(int, tyProc__T08W9bgbY4bOv2q64h6irpw) (void* m, NCSTRING n, void* o);
typedef N_CDECL_PTR(void*, tyProc__uQWqJp3WAx8fOY1h9aCwjIg) (void* callable_object, void* args, void* kw);
typedef N_CDECL_PTR(int, tyProc__fbYpjfe38x3ujjAmVRbI1Q) (void* o);
typedef N_CDECL_PTR(void*, tyProc__YezmFzxOOyM9cb11Eoq1Elg) (void* o, NCSTRING name);
typedef N_CDECL_PTR(void*, tyProc__jvPpjMAkI9bwM1B9apOphnlA) (void* o);
typedef N_CDECL_PTR(void*, tyProc__VQ1ysQk017myXMGb79cPTVw) (void* o, void* k);
typedef N_CDECL_PTR(int, tyProc__7LMjBc4zOHVIsNdulNv7QQ) (void* o, void* k, void* v);
typedef N_CDECL_PTR(int, tyProc__eoRP3F9aLT3mtHj6OkcMSyQ) (void* a, void* b, int op);
typedef N_CDECL_PTR(int, tyProc__8hR9arLDkUs9ag3Pt9bWtjfsg) (void* o, tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w* b, int flags);
typedef N_CDECL_PTR(void, tyProc__vFvpnKOere9bRFN9czzMRlTA) (tyObject_RawPyBuffer__0qyRdSZKtLACJ1u4qMMP2w* b);
typedef N_CDECL_PTR(void*, tyProc__BZ6N5NNdHcK05FTDxQbEWw) (NCSTRING name, void* base, void* dict);
typedef N_CDECL_PTR(NI64, tyProc__mIlNZ9aGaphVJCyIIofK8mg) (void* l);
typedef N_CDECL_PTR(double, tyProc__2su9b9chqHYibM7sMkbSaSkA) (void* l);
typedef N_CDECL_PTR(void*, tyProc__Fc4ZUx59aQs10dLxeMQ50mw) (long v);
typedef N_CDECL_PTR(int, tyProc__i2exZ7Vtp648U9crOFcq9beQ) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* t1, tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* t2);
struct tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA {
NF re;
NF im;
};
typedef N_CDECL_PTR(tyObject_Complex__zWadV1X9aMO7qS9bsQFB0JFA, tyProc__N1A5ZvDSgO9c9aRXmVqfn9bAw) (void* op);
typedef N_CDECL_PTR(int, tyProc__3FKLKFzOaK7FD6dRLWM6Jw) (void* o, NIM_CHAR** s, NI* len);
typedef N_CDECL_PTR(void*, tyProc__YDKrw1adv61oVQkQhbYyaA) (NCSTRING s);
typedef N_CDECL_PTR(int, tyProc__B2MjSeo07a72ynTQRVYFKw) (void* o, NCSTRING s);
typedef N_CDECL_PTR(NCSTRING, tyProc__p1X2BwWx9a3wsChhykvf29aA) (void* o);
typedef N_CDECL_PTR(void*, tyProc__NzboHqZVJcbdtVGYrOosXQ) (void);
typedef N_CDECL_PTR(int, tyProc__MTei9bsKjha0o1cISO9aLMDg) (void* o, void* k);
typedef N_NIMCALL_PTR(void, tyProc__4SVlZZPmetqBimNsH9cHcOA) (void* o);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc__WYY8i0I79agBofnUcEGCfig) (void* o, NCSTRING s);
typedef N_CDECL_PTR(void, tyProc__32w2ZypAyMWuajvi2Jt79cg) (void* o);
typedef N_CDECL_PTR(void*, tyProc__jcEovQ2rZUNUsYxohT50Ug) (void* p, NCSTRING name, tyProc__32w2ZypAyMWuajvi2Jt79cg destr);
typedef N_CDECL_PTR(void*, tyProc__9b2qzlf3LCKK0JvThQT1atg) (tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw* md, void* self, void* module);
typedef N_CDECL_PTR(void, tyProc__U0oVFt576Ze44Q9a3eZc5wg) (void** ptype, void** pvalue, void** ptraceback);
struct tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig {
void* module;
tyProc__SsjMo29bx9bP5kwe2xgM3Scg Py_BuildValue;
tyProc__4wJmT85lsn175X0dPNQv7w PyTuple_New;
tyProc__YRQqZC12s3573tRGP8MV3g PyTuple_Size;
tyProc__oPIasAghCTvCKmvkMeB1xQ PyTuple_GetItem;
tyProc__6slETyyIDJuDOSqkO0hUXA PyTuple_SetItem;
void* Py_None;
tyProc__tgpXIILGoVcO9bvYnz9azTVQ PyType_Ready;
tyProc__eYT4U6bGFqFBUxk9b15mfOA PyType_GenericNew;
tyProc__T08W9bgbY4bOv2q64h6irpw PyModule_AddObject;
tyProc__4wJmT85lsn175X0dPNQv7w PyList_New;
tyProc__YRQqZC12s3573tRGP8MV3g PyList_Size;
tyProc__oPIasAghCTvCKmvkMeB1xQ PyList_GetItem;
tyProc__6slETyyIDJuDOSqkO0hUXA PyList_SetItem;
tyProc__uQWqJp3WAx8fOY1h9aCwjIg PyObject_Call;
tyProc__fbYpjfe38x3ujjAmVRbI1Q PyObject_IsTrue;
tyProc__YezmFzxOOyM9cb11Eoq1Elg PyObject_GetAttrString;
tyProc__T08W9bgbY4bOv2q64h6irpw PyObject_SetAttrString;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyObject_Dir;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyObject_Str;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyObject_GetIter;
tyProc__VQ1ysQk017myXMGb79cPTVw PyObject_GetItem;
tyProc__7LMjBc4zOHVIsNdulNv7QQ PyObject_SetItem;
tyProc__eoRP3F9aLT3mtHj6OkcMSyQ PyObject_RichCompareBool;
tyProc__8hR9arLDkUs9ag3Pt9bWtjfsg PyObject_GetBuffer;
tyProc__vFvpnKOere9bRFN9czzMRlTA PyBuffer_Release;
tyProc__BZ6N5NNdHcK05FTDxQbEWw PyErr_NewException;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyIter_Next;
tyProc__mIlNZ9aGaphVJCyIIofK8mg PyLong_AsLongLong;
tyProc__2su9b9chqHYibM7sMkbSaSkA PyFloat_AsDouble;
tyProc__Fc4ZUx59aQs10dLxeMQ50mw PyBool_FromLong;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyFloat_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyComplex_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyCapsule_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyTuple_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyList_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyBytes_Type;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyUnicode_Type;
tyProc__i2exZ7Vtp648U9crOFcq9beQ PyType_IsSubtype;
tyProc__N1A5ZvDSgO9c9aRXmVqfn9bAw PyComplex_AsCComplex;
tyProc__2su9b9chqHYibM7sMkbSaSkA PyComplex_RealAsDouble;
tyProc__2su9b9chqHYibM7sMkbSaSkA PyComplex_ImagAsDouble;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyUnicode_AsUTF8String;
tyProc__3FKLKFzOaK7FD6dRLWM6Jw PyBytes_AsStringAndSize;
tyProc__YDKrw1adv61oVQkQhbYyaA PyUnicode_FromString;
tyProc__B2MjSeo07a72ynTQRVYFKw PyUnicode_CompareWithASCIIString;
tyProc__p1X2BwWx9a3wsChhykvf29aA PyString_AsString;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* PyDict_Type;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyDict_New;
tyProc__YRQqZC12s3573tRGP8MV3g PyDict_Size;
tyProc__YezmFzxOOyM9cb11Eoq1Elg PyDict_GetItemString;
tyProc__T08W9bgbY4bOv2q64h6irpw PyDict_SetItemString;
tyProc__VQ1ysQk017myXMGb79cPTVw PyDict_GetItem;
tyProc__7LMjBc4zOHVIsNdulNv7QQ PyDict_SetItem;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyDict_Keys;
tyProc__jvPpjMAkI9bwM1B9apOphnlA PyDict_Values;
tyProc__MTei9bsKjha0o1cISO9aLMDg PyDict_Contains;
tyProc__4SVlZZPmetqBimNsH9cHcOA PyDealloc;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ PyErr_Clear;
tyProc__WYY8i0I79agBofnUcEGCfig PyErr_SetString;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyErr_Occurred;
void* PyExc_TypeError;
tyProc__jcEovQ2rZUNUsYxohT50Ug PyCapsule_New;
tyProc__YezmFzxOOyM9cb11Eoq1Elg PyCapsule_GetPointer;
tyProc__YDKrw1adv61oVQkQhbYyaA PyImport_ImportModule;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyEval_GetBuiltins;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyEval_GetGlobals;
tyProc__NzboHqZVJcbdtVGYrOosXQ PyEval_GetLocals;
tyProc__9b2qzlf3LCKK0JvThQT1atg PyCFunction_NewEx;
NI pythonVersion;
tyProc__U0oVFt576Ze44Q9a3eZc5wg PyErr_Fetch;
tyProc__U0oVFt576Ze44Q9a3eZc5wg PyErr_NormalizeException;
tyProc__MTei9bsKjha0o1cISO9aLMDg PyErr_GivenExceptionMatches;
void* PyExc_BaseException;
void* PyExc_Exception;
void* PyExc_ArithmeticError;
void* PyExc_FloatingPointError;
void* PyExc_OverflowError;
void* PyExc_ZeroDivisionError;
void* PyExc_AssertionError;
void* PyExc_OSError;
void* PyExc_IOError;
void* PyExc_ValueError;
void* PyExc_EOFError;
void* PyExc_MemoryError;
void* PyExc_IndexError;
void* PyExc_KeyError;
void* NimPyException;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A {
NimStringDesc* name;
void* initAddr2;
void* initAddr3;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg {
NI ob_refcnt;
void* ob_type;
};
struct tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw {
  tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg Sup;
NI ob_size;
};
typedef N_CDECL_PTR(int, tyProc__rNiGphbUW4RHd2WIj64deg) (void* o, FILE* f, int c);
typedef N_CDECL_PTR(void*, tyProc__k4RBH32nrpDxtGF9acg45zw) (void* a, void* b, int c);
typedef N_CDECL_PTR(void*, tyProc__Cj3MN9a7OA9a51xOtsYjEwBg) (tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* typ, NI sz);
struct tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g {
  tyObject_PyObjectVarHeadObj__5fAkl5kIcYJNl6VvYzZdMw Sup;
NCSTRING tp_name;
NI tp_basicsize;
NI tp_itemsize;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_dealloc;
tyProc__rNiGphbUW4RHd2WIj64deg tp_print;
tyProc__YezmFzxOOyM9cb11Eoq1Elg tp_getattr;
tyProc__T08W9bgbY4bOv2q64h6irpw tp_setattr;
void* tp_as_async;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_repr;
void* tp_as_number;
void* tp_as_sequence;
void* tp_as_mapping;
void* tp_hash;
void* tp_call;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_str;
tyProc__VQ1ysQk017myXMGb79cPTVw tp_getattro;
tyProc__7LMjBc4zOHVIsNdulNv7QQ tp_setattro;
void* tp_as_buffer;
unsigned long tp_flags;
NCSTRING tp_doc;
void* tp_traverse;
void* tp_clear;
tyProc__k4RBH32nrpDxtGF9acg45zw tp_richcompare;
NI tp_weaklistoffset;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_iter;
tyProc__jvPpjMAkI9bwM1B9apOphnlA tp_iternext;
tyObject_PyMethodDef__9aWi1PsmvCuTKIYDHHnhfcw* tp_methods;
tyObject_PyMemberDef__WC29aEeHi2Pdy9c4AkllcBTg* tp_members;
void* tp_getset;
tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* tp_base;
void* tp_dict;
tyProc__uQWqJp3WAx8fOY1h9aCwjIg tp_descr_get;
tyProc__7LMjBc4zOHVIsNdulNv7QQ tp_descr_set;
NI tp_dictoffset;
tyProc__7LMjBc4zOHVIsNdulNv7QQ tp_init;
tyProc__Cj3MN9a7OA9a51xOtsYjEwBg tp_alloc;
tyProc__eYT4U6bGFqFBUxk9b15mfOA tp_new;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_free;
void* tp_is_gc;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* tp_bases;
void* tp_mro;
void* tp_cache;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* tp_subclasses;
tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* tp_weaklist;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_del;
unsigned int tp_version_tag;
tyProc__32w2ZypAyMWuajvi2Jt79cg tp_finalize;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__M73GJ9bOx1XdoIRnhIyhqTQ {
  TGenericSeq Sup;
  tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef__cCIKHidpwSneftqUUnSNWg)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__XnAUe69cYg8yQhnmiRJUnHw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tySequence__M73GJ9bOx1XdoIRnhIyhqTQ)(void* p, NI op);
static N_NIMCALL(void, TM__XnAUe69cYg8yQhnmiRJUnHw_5)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__ALH9bdNwXEzg7MPq4PA9csvw)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(void, symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw)(NCSTRING s);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, deallocPythonObj__g4g2BXzYUyHtyZiBrSD7aw)(void* p);
static N_INLINE(tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*, to__4gaYCHYBaCTIs6wfSrqsEApy_lib)(void* p);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
NU pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q;
tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig* pyLib__nxKBiAukGMNwnUq9bpn9adyw;
TNimType NTI__bTw708kK89b8Vj9cmSu9a4zig_;
extern TNimType NTI__vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI__SsjMo29bx9bP5kwe2xgM3Scg_;
TNimType NTI__4wJmT85lsn175X0dPNQv7w_;
TNimType NTI__YRQqZC12s3573tRGP8MV3g_;
TNimType NTI__oPIasAghCTvCKmvkMeB1xQ_;
TNimType NTI__6slETyyIDJuDOSqkO0hUXA_;
TNimType NTI__tgpXIILGoVcO9bvYnz9azTVQ_;
TNimType NTI__eYT4U6bGFqFBUxk9b15mfOA_;
TNimType NTI__T08W9bgbY4bOv2q64h6irpw_;
TNimType NTI__uQWqJp3WAx8fOY1h9aCwjIg_;
TNimType NTI__fbYpjfe38x3ujjAmVRbI1Q_;
TNimType NTI__YezmFzxOOyM9cb11Eoq1Elg_;
TNimType NTI__jvPpjMAkI9bwM1B9apOphnlA_;
TNimType NTI__VQ1ysQk017myXMGb79cPTVw_;
TNimType NTI__7LMjBc4zOHVIsNdulNv7QQ_;
TNimType NTI__eoRP3F9aLT3mtHj6OkcMSyQ_;
TNimType NTI__8hR9arLDkUs9ag3Pt9bWtjfsg_;
TNimType NTI__vFvpnKOere9bRFN9czzMRlTA_;
TNimType NTI__BZ6N5NNdHcK05FTDxQbEWw_;
TNimType NTI__mIlNZ9aGaphVJCyIIofK8mg_;
TNimType NTI__2su9b9chqHYibM7sMkbSaSkA_;
TNimType NTI__Fc4ZUx59aQs10dLxeMQ50mw_;
extern TNimType NTI__dgEY47TsFEQv355iEJP9bPA_;
TNimType NTI__i2exZ7Vtp648U9crOFcq9beQ_;
TNimType NTI__N1A5ZvDSgO9c9aRXmVqfn9bAw_;
TNimType NTI__3FKLKFzOaK7FD6dRLWM6Jw_;
TNimType NTI__YDKrw1adv61oVQkQhbYyaA_;
TNimType NTI__B2MjSeo07a72ynTQRVYFKw_;
TNimType NTI__p1X2BwWx9a3wsChhykvf29aA_;
TNimType NTI__NzboHqZVJcbdtVGYrOosXQ_;
TNimType NTI__MTei9bsKjha0o1cISO9aLMDg_;
TNimType NTI__4SVlZZPmetqBimNsH9cHcOA_;
TNimType NTI__ln4kdL5W9bbX4a1xl8nnVXQ_;
TNimType NTI__WYY8i0I79agBofnUcEGCfig_;
TNimType NTI__jcEovQ2rZUNUsYxohT50Ug_;
TNimType NTI__9b2qzlf3LCKK0JvThQT1atg_;
extern TNimType NTI__rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI__U0oVFt576Ze44Q9a3eZc5wg_;
TNimType NTI__cCIKHidpwSneftqUUnSNWg_;
tySequence__M73GJ9bOx1XdoIRnhIyhqTQ* exportedModules__8kMAOMTFJYz2QnlnegLbYw;
TNimType NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_;
extern TNimType NTI__77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI__M73GJ9bOx1XdoIRnhIyhqTQ_;
extern TNimType NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_;
extern TNimType NTI__XEycrCsme5C8CVWAYEcdBQ_;
STRING_LITERAL(TM__XnAUe69cYg8yQhnmiRJUnHw_6, "py_lib.nim(158, 9) `not m.isNil` ", 33);
STRING_LITERAL(TM__XnAUe69cYg8yQhnmiRJUnHw_7, "Symbol not loaded: ", 19);
static N_NIMCALL(void, Marker_tyRef__cCIKHidpwSneftqUUnSNWg)(void* p, NI op) {
	tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig* a;
	a = (tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*)p;
}
static N_NIMCALL(void, TM__XnAUe69cYg8yQhnmiRJUnHw_3)(void) {
	nimGCvisit((void*)pyLib__nxKBiAukGMNwnUq9bpn9adyw, 0);
}
static N_NIMCALL(void, Marker_tySequence__M73GJ9bOx1XdoIRnhIyhqTQ)(void* p, NI op) {
	tySequence__M73GJ9bOx1XdoIRnhIyhqTQ* a;
	NI T1_;
	a = (tySequence__M73GJ9bOx1XdoIRnhIyhqTQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].name, op);
	}
}
static N_NIMCALL(void, TM__XnAUe69cYg8yQhnmiRJUnHw_5)(void) {
	nimGCvisit((void*)exportedModules__8kMAOMTFJYz2QnlnegLbYw, 0);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw)(NCSTRING s) {	Exception* eX60gensym358785_;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	eX60gensym358785_ = (Exception*)0;
	eX60gensym358785_ = (Exception*) newObj((&NTI__vU9aO9cTqOMn6CBzhV8rX7Sw_), sizeof(Exception));
	(*eX60gensym358785_).Sup.m_type = (&NTI__XEycrCsme5C8CVWAYEcdBQ_);
	(*eX60gensym358785_).name = "Exception";
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = cstrToNimstr(s);
	T1_ = rawNewString((T2_ ? T2_->Sup.len : 0) + 19);
appendString(T1_, ((NimStringDesc*) &TM__XnAUe69cYg8yQhnmiRJUnHw_7));
appendString(T1_, T2_);
	(*eX60gensym358785_).message = T1_;
	(*eX60gensym358785_).parent = NIM_NIL;
	raiseExceptionEx((Exception*)eX60gensym358785_, "Exception", "symNotLoadedErr", "py_lib.nim", 155);
}
static N_INLINE(tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*, to__4gaYCHYBaCTIs6wfSrqsEApy_lib)(void* p) {	tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* result;
	result = (tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*)0;
	result = ((tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg*) ((NU)((NU64)(((NU) (ptrdiff_t) (p))) + (NU64)(pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, deallocPythonObj__g4g2BXzYUyHtyZiBrSD7aw)(void* p) {	tyObject_PyObjectObj__aD5pkFWInXrZXinZ42cDEg* ob;
	tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g* t;
	ob = to__4gaYCHYBaCTIs6wfSrqsEApy_lib(p);
	t = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) ((*ob).ob_type));
	(*t).tp_dealloc(((void*) (p)));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*, loadPyLibFromModule__bRaZxNTpbKALHcCxxa9aNCA)(void* m) {	tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig* result;
	tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig* pl;
	void* T16_;
	void* T21_;
	void* T26_;
	void* T31_;
	void* T36_;
	void* T41_;
	void* T46_;
	void* T51_;
	void* T56_;
	void* T61_;
	void* T66_;
	void* T71_;
	void* T76_;
	void* T81_;
	void* T86_;
	void* T91_;
	void* T96_;
	void* T101_;
	void* T106_;
	void* T111_;
	void* T116_;
	void* T121_;
	void* T126_;
	void* T131_;
	void* T132_;
	void* T133_;
	void* T138_;
	void* T143_;
	void* T148_;
	void* T153_;
	void* T158_;
	void* T163_;
	void* T168_;
	void* T173_;
	void* T178_;
	void* T183_;
	void* T193_;
	void* T203_;
	void* T208_;
	void* T223_;
	void* T233_;
	void* T248_;
	void* T258_;
	void* T263_;
	void* T268_;
	void* T273_;
	void* T278_;
	void* T283_;
	void* T288_;
	void* T293_;
	void* T298_;
	void* T303_;
	void* T313_;
	void* T318_;
	void* T323_;
	void* T328_;
	void* T333_;
	void* T338_;
	void* T343_;
	void* T348_;
	void* T353_;
	void* T358_;
	void* T363_;
	void* T368_;
	void* T373_;
	void* T378_;
	void* T383_;
	void* T388_;
	void* T393_;
	void* T398_;
	void* T403_;
	void* T408_;
	void* T413_;
	void* T418_;
	void* T423_;
	void* T428_;
	void* T433_;
	void* T438_;
	void* T443_;
	result = (tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*)0;
	{
		if (!!(!((m == 0)))) goto LA3_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(((NimStringDesc*) &TM__XnAUe69cYg8yQhnmiRJUnHw_6));
	}
	LA3_: ;
	result = (tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*) newObj((&NTI__cCIKHidpwSneftqUUnSNWg_), sizeof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig));
	pl = result;
	(*pl).module = m;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		void* T9_;
		void* T11_;
		void* T13_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T9_ = (void*)0;
		T9_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyModule_Create2");
		T8_ = (T9_ == 0);
		if (T8_) goto LA10_;
		T11_ = (void*)0;
		T11_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "Py_InitModule4_64");
		T8_ = (T11_ == 0);
		LA10_: ;
		T7_ = T8_;
		if (T7_) goto LA12_;
		T13_ = (void*)0;
		T13_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "Py_InitModule4");
		T7_ = (T13_ == 0);
		LA12_: ;
		if (!!(T7_)) goto LA14_;
		pyObjectStartOffset__g20dGCi2MffsHqmxIpqX7Q = ((NU) 16);
	}
	LA14_: ;
	T16_ = (void*)0;
	T16_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "_Py_BuildValue_SizeT");
	(*pl).Py_BuildValue = ((tyProc__SsjMo29bx9bP5kwe2xgM3Scg) (T16_));
	{
		if (!((*pl).Py_BuildValue == 0)) goto LA19_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("_Py_BuildValue_SizeT");
	}
	LA19_: ;
	T21_ = (void*)0;
	T21_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyTuple_New");
	(*pl).PyTuple_New = ((tyProc__4wJmT85lsn175X0dPNQv7w) (T21_));
	{
		if (!((*pl).PyTuple_New == 0)) goto LA24_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyTuple_New");
	}
	LA24_: ;
	T26_ = (void*)0;
	T26_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyTuple_Size");
	(*pl).PyTuple_Size = ((tyProc__YRQqZC12s3573tRGP8MV3g) (T26_));
	{
		if (!((*pl).PyTuple_Size == 0)) goto LA29_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyTuple_Size");
	}
	LA29_: ;
	T31_ = (void*)0;
	T31_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyTuple_GetItem");
	(*pl).PyTuple_GetItem = ((tyProc__oPIasAghCTvCKmvkMeB1xQ) (T31_));
	{
		if (!((*pl).PyTuple_GetItem == 0)) goto LA34_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyTuple_GetItem");
	}
	LA34_: ;
	T36_ = (void*)0;
	T36_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyTuple_SetItem");
	(*pl).PyTuple_SetItem = ((tyProc__6slETyyIDJuDOSqkO0hUXA) (T36_));
	{
		if (!((*pl).PyTuple_SetItem == 0)) goto LA39_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyTuple_SetItem");
	}
	LA39_: ;
	T41_ = (void*)0;
	T41_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "_Py_NoneStruct");
	(*pl).Py_None = ((void*) (T41_));
	{
		if (!((*pl).Py_None == 0)) goto LA44_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("_Py_NoneStruct");
	}
	LA44_: ;
	T46_ = (void*)0;
	T46_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyType_Ready");
	(*pl).PyType_Ready = ((tyProc__tgpXIILGoVcO9bvYnz9azTVQ) (T46_));
	{
		if (!((*pl).PyType_Ready == 0)) goto LA49_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyType_Ready");
	}
	LA49_: ;
	T51_ = (void*)0;
	T51_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyType_GenericNew");
	(*pl).PyType_GenericNew = ((tyProc__eYT4U6bGFqFBUxk9b15mfOA) (T51_));
	{
		if (!((*pl).PyType_GenericNew == 0)) goto LA54_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyType_GenericNew");
	}
	LA54_: ;
	T56_ = (void*)0;
	T56_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyModule_AddObject");
	(*pl).PyModule_AddObject = ((tyProc__T08W9bgbY4bOv2q64h6irpw) (T56_));
	{
		if (!((*pl).PyModule_AddObject == 0)) goto LA59_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyModule_AddObject");
	}
	LA59_: ;
	T61_ = (void*)0;
	T61_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyList_New");
	(*pl).PyList_New = ((tyProc__4wJmT85lsn175X0dPNQv7w) (T61_));
	{
		if (!((*pl).PyList_New == 0)) goto LA64_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyList_New");
	}
	LA64_: ;
	T66_ = (void*)0;
	T66_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyList_Size");
	(*pl).PyList_Size = ((tyProc__YRQqZC12s3573tRGP8MV3g) (T66_));
	{
		if (!((*pl).PyList_Size == 0)) goto LA69_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyList_Size");
	}
	LA69_: ;
	T71_ = (void*)0;
	T71_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyList_GetItem");
	(*pl).PyList_GetItem = ((tyProc__oPIasAghCTvCKmvkMeB1xQ) (T71_));
	{
		if (!((*pl).PyList_GetItem == 0)) goto LA74_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyList_GetItem");
	}
	LA74_: ;
	T76_ = (void*)0;
	T76_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyList_SetItem");
	(*pl).PyList_SetItem = ((tyProc__6slETyyIDJuDOSqkO0hUXA) (T76_));
	{
		if (!((*pl).PyList_SetItem == 0)) goto LA79_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyList_SetItem");
	}
	LA79_: ;
	T81_ = (void*)0;
	T81_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_Call");
	(*pl).PyObject_Call = ((tyProc__uQWqJp3WAx8fOY1h9aCwjIg) (T81_));
	{
		if (!((*pl).PyObject_Call == 0)) goto LA84_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_Call");
	}
	LA84_: ;
	T86_ = (void*)0;
	T86_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_IsTrue");
	(*pl).PyObject_IsTrue = ((tyProc__fbYpjfe38x3ujjAmVRbI1Q) (T86_));
	{
		if (!((*pl).PyObject_IsTrue == 0)) goto LA89_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_IsTrue");
	}
	LA89_: ;
	T91_ = (void*)0;
	T91_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_GetAttrString");
	(*pl).PyObject_GetAttrString = ((tyProc__YezmFzxOOyM9cb11Eoq1Elg) (T91_));
	{
		if (!((*pl).PyObject_GetAttrString == 0)) goto LA94_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_GetAttrString");
	}
	LA94_: ;
	T96_ = (void*)0;
	T96_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_SetAttrString");
	(*pl).PyObject_SetAttrString = ((tyProc__T08W9bgbY4bOv2q64h6irpw) (T96_));
	{
		if (!((*pl).PyObject_SetAttrString == 0)) goto LA99_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_SetAttrString");
	}
	LA99_: ;
	T101_ = (void*)0;
	T101_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_Dir");
	(*pl).PyObject_Dir = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T101_));
	{
		if (!((*pl).PyObject_Dir == 0)) goto LA104_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_Dir");
	}
	LA104_: ;
	T106_ = (void*)0;
	T106_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_Str");
	(*pl).PyObject_Str = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T106_));
	{
		if (!((*pl).PyObject_Str == 0)) goto LA109_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_Str");
	}
	LA109_: ;
	T111_ = (void*)0;
	T111_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_GetIter");
	(*pl).PyObject_GetIter = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T111_));
	{
		if (!((*pl).PyObject_GetIter == 0)) goto LA114_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_GetIter");
	}
	LA114_: ;
	T116_ = (void*)0;
	T116_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_GetItem");
	(*pl).PyObject_GetItem = ((tyProc__VQ1ysQk017myXMGb79cPTVw) (T116_));
	{
		if (!((*pl).PyObject_GetItem == 0)) goto LA119_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_GetItem");
	}
	LA119_: ;
	T121_ = (void*)0;
	T121_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_SetItem");
	(*pl).PyObject_SetItem = ((tyProc__7LMjBc4zOHVIsNdulNv7QQ) (T121_));
	{
		if (!((*pl).PyObject_SetItem == 0)) goto LA124_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_SetItem");
	}
	LA124_: ;
	T126_ = (void*)0;
	T126_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_RichCompareBool");
	(*pl).PyObject_RichCompareBool = ((tyProc__eoRP3F9aLT3mtHj6OkcMSyQ) (T126_));
	{
		if (!((*pl).PyObject_RichCompareBool == 0)) goto LA129_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyObject_RichCompareBool");
	}
	LA129_: ;
	T131_ = (void*)0;
	T131_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyObject_GetBuffer");
	(*pl).PyObject_GetBuffer = ((tyProc__8hR9arLDkUs9ag3Pt9bWtjfsg) (T131_));
	T132_ = (void*)0;
	T132_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyBuffer_Release");
	(*pl).PyBuffer_Release = ((tyProc__vFvpnKOere9bRFN9czzMRlTA) (T132_));
	T133_ = (void*)0;
	T133_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyIter_Next");
	(*pl).PyIter_Next = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T133_));
	{
		if (!((*pl).PyIter_Next == 0)) goto LA136_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyIter_Next");
	}
	LA136_: ;
	T138_ = (void*)0;
	T138_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyLong_AsLongLong");
	(*pl).PyLong_AsLongLong = ((tyProc__mIlNZ9aGaphVJCyIIofK8mg) (T138_));
	{
		if (!((*pl).PyLong_AsLongLong == 0)) goto LA141_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyLong_AsLongLong");
	}
	LA141_: ;
	T143_ = (void*)0;
	T143_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyFloat_AsDouble");
	(*pl).PyFloat_AsDouble = ((tyProc__2su9b9chqHYibM7sMkbSaSkA) (T143_));
	{
		if (!((*pl).PyFloat_AsDouble == 0)) goto LA146_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyFloat_AsDouble");
	}
	LA146_: ;
	T148_ = (void*)0;
	T148_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyBool_FromLong");
	(*pl).PyBool_FromLong = ((tyProc__Fc4ZUx59aQs10dLxeMQ50mw) (T148_));
	{
		if (!((*pl).PyBool_FromLong == 0)) goto LA151_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyBool_FromLong");
	}
	LA151_: ;
	T153_ = (void*)0;
	T153_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyFloat_Type");
	(*pl).PyFloat_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T153_));
	{
		if (!((*pl).PyFloat_Type == 0)) goto LA156_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyFloat_Type");
	}
	LA156_: ;
	T158_ = (void*)0;
	T158_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyComplex_Type");
	(*pl).PyComplex_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T158_));
	{
		if (!((*pl).PyComplex_Type == 0)) goto LA161_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyComplex_Type");
	}
	LA161_: ;
	T163_ = (void*)0;
	T163_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyCapsule_Type");
	(*pl).PyCapsule_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T163_));
	{
		if (!((*pl).PyCapsule_Type == 0)) goto LA166_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyCapsule_Type");
	}
	LA166_: ;
	T168_ = (void*)0;
	T168_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyTuple_Type");
	(*pl).PyTuple_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T168_));
	{
		if (!((*pl).PyTuple_Type == 0)) goto LA171_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyTuple_Type");
	}
	LA171_: ;
	T173_ = (void*)0;
	T173_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyList_Type");
	(*pl).PyList_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T173_));
	{
		if (!((*pl).PyList_Type == 0)) goto LA176_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyList_Type");
	}
	LA176_: ;
	T178_ = (void*)0;
	T178_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyUnicode_Type");
	(*pl).PyUnicode_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T178_));
	{
		if (!((*pl).PyUnicode_Type == 0)) goto LA181_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyUnicode_Type");
	}
	LA181_: ;
	T183_ = (void*)0;
	T183_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyBytes_Type");
	(*pl).PyBytes_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T183_));
	{
		void* T188_;
		if (!((*pl).PyBytes_Type == 0)) goto LA186_;
		T188_ = (void*)0;
		T188_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyString_Type");
		(*pl).PyBytes_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T188_));
		{
			if (!((*pl).PyBytes_Type == 0)) goto LA191_;
			symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyString_Type");
		}
		LA191_: ;
	}
	LA186_: ;
	T193_ = (void*)0;
	T193_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyUnicode_FromString");
	(*pl).PyUnicode_FromString = ((tyProc__YDKrw1adv61oVQkQhbYyaA) (T193_));
	{
		void* T198_;
		if (!((*pl).PyUnicode_FromString == 0)) goto LA196_;
		T198_ = (void*)0;
		T198_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyString_FromString");
		(*pl).PyUnicode_FromString = ((tyProc__YDKrw1adv61oVQkQhbYyaA) (T198_));
		{
			if (!((*pl).PyUnicode_FromString == 0)) goto LA201_;
			symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyString_FromString");
		}
		LA201_: ;
	}
	LA196_: ;
	T203_ = (void*)0;
	T203_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyType_IsSubtype");
	(*pl).PyType_IsSubtype = ((tyProc__i2exZ7Vtp648U9crOFcq9beQ) (T203_));
	{
		if (!((*pl).PyType_IsSubtype == 0)) goto LA206_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyType_IsSubtype");
	}
	LA206_: ;
	T208_ = (void*)0;
	T208_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyComplex_AsCComplex");
	(*pl).PyComplex_AsCComplex = ((tyProc__N1A5ZvDSgO9c9aRXmVqfn9bAw) (T208_));
	{
		void* T213_;
		void* T218_;
		if (!((*pl).PyComplex_AsCComplex == 0)) goto LA211_;
		T213_ = (void*)0;
		T213_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyComplex_RealAsDouble");
		(*pl).PyComplex_RealAsDouble = ((tyProc__2su9b9chqHYibM7sMkbSaSkA) (T213_));
		{
			if (!((*pl).PyComplex_RealAsDouble == 0)) goto LA216_;
			symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyComplex_RealAsDouble");
		}
		LA216_: ;
		T218_ = (void*)0;
		T218_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyComplex_ImagAsDouble");
		(*pl).PyComplex_ImagAsDouble = ((tyProc__2su9b9chqHYibM7sMkbSaSkA) (T218_));
		{
			if (!((*pl).PyComplex_ImagAsDouble == 0)) goto LA221_;
			symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyComplex_ImagAsDouble");
		}
		LA221_: ;
	}
	LA211_: ;
	T223_ = (void*)0;
	T223_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyUnicode_CompareWithASCIIString");
	(*pl).PyUnicode_CompareWithASCIIString = ((tyProc__B2MjSeo07a72ynTQRVYFKw) (T223_));
	{
		void* T228_;
		if (!((*pl).PyUnicode_CompareWithASCIIString == 0)) goto LA226_;
		T228_ = (void*)0;
		T228_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyString_AsString");
		(*pl).PyString_AsString = ((tyProc__p1X2BwWx9a3wsChhykvf29aA) (T228_));
		{
			if (!((*pl).PyString_AsString == 0)) goto LA231_;
			symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyString_AsString");
		}
		LA231_: ;
	}
	LA226_: ;
	T233_ = (void*)0;
	T233_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyUnicode_AsUTF8String");
	(*pl).PyUnicode_AsUTF8String = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T233_));
	{
		void* T238_;
		if (!((*pl).PyUnicode_AsUTF8String == 0)) goto LA236_;
		T238_ = (void*)0;
		T238_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyUnicodeUCS4_AsUTF8String");
		(*pl).PyUnicode_AsUTF8String = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T238_));
		{
			void* T243_;
			if (!((*pl).PyUnicode_AsUTF8String == 0)) goto LA241_;
			T243_ = (void*)0;
			T243_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyUnicodeUCS2_AsUTF8String");
			(*pl).PyUnicode_AsUTF8String = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T243_));
			{
				if (!((*pl).PyUnicode_AsUTF8String == 0)) goto LA246_;
				symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyUnicodeUCS2_AsUTF8String");
			}
			LA246_: ;
		}
		LA241_: ;
	}
	LA236_: ;
	(*pl).pythonVersion = ((NI) 3);
	T248_ = (void*)0;
	T248_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyBytes_AsStringAndSize");
	(*pl).PyBytes_AsStringAndSize = ((tyProc__3FKLKFzOaK7FD6dRLWM6Jw) (T248_));
	{
		void* T253_;
		if (!((*pl).PyBytes_AsStringAndSize == 0)) goto LA251_;
		T253_ = (void*)0;
		T253_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyString_AsStringAndSize");
		(*pl).PyBytes_AsStringAndSize = ((tyProc__3FKLKFzOaK7FD6dRLWM6Jw) (T253_));
		{
			if (!((*pl).PyBytes_AsStringAndSize == 0)) goto LA256_;
			symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyString_AsStringAndSize");
		}
		LA256_: ;
		(*pl).pythonVersion = ((NI) 2);
	}
	LA251_: ;
	T258_ = (void*)0;
	T258_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_Type");
	(*pl).PyDict_Type = ((tyObject_PyTypeObject3Obj__cRsC9bGvH9bX6A9aVx8UB6I5g*) (T258_));
	{
		if (!((*pl).PyDict_Type == 0)) goto LA261_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_Type");
	}
	LA261_: ;
	T263_ = (void*)0;
	T263_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_New");
	(*pl).PyDict_New = ((tyProc__NzboHqZVJcbdtVGYrOosXQ) (T263_));
	{
		if (!((*pl).PyDict_New == 0)) goto LA266_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_New");
	}
	LA266_: ;
	T268_ = (void*)0;
	T268_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_Size");
	(*pl).PyDict_Size = ((tyProc__YRQqZC12s3573tRGP8MV3g) (T268_));
	{
		if (!((*pl).PyDict_Size == 0)) goto LA271_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_Size");
	}
	LA271_: ;
	T273_ = (void*)0;
	T273_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_GetItemString");
	(*pl).PyDict_GetItemString = ((tyProc__YezmFzxOOyM9cb11Eoq1Elg) (T273_));
	{
		if (!((*pl).PyDict_GetItemString == 0)) goto LA276_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_GetItemString");
	}
	LA276_: ;
	T278_ = (void*)0;
	T278_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_SetItemString");
	(*pl).PyDict_SetItemString = ((tyProc__T08W9bgbY4bOv2q64h6irpw) (T278_));
	{
		if (!((*pl).PyDict_SetItemString == 0)) goto LA281_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_SetItemString");
	}
	LA281_: ;
	T283_ = (void*)0;
	T283_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_GetItem");
	(*pl).PyDict_GetItem = ((tyProc__VQ1ysQk017myXMGb79cPTVw) (T283_));
	{
		if (!((*pl).PyDict_GetItem == 0)) goto LA286_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_GetItem");
	}
	LA286_: ;
	T288_ = (void*)0;
	T288_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_SetItem");
	(*pl).PyDict_SetItem = ((tyProc__7LMjBc4zOHVIsNdulNv7QQ) (T288_));
	{
		if (!((*pl).PyDict_SetItem == 0)) goto LA291_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_SetItem");
	}
	LA291_: ;
	T293_ = (void*)0;
	T293_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_Keys");
	(*pl).PyDict_Keys = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T293_));
	{
		if (!((*pl).PyDict_Keys == 0)) goto LA296_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_Keys");
	}
	LA296_: ;
	T298_ = (void*)0;
	T298_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_Values");
	(*pl).PyDict_Values = ((tyProc__jvPpjMAkI9bwM1B9apOphnlA) (T298_));
	{
		if (!((*pl).PyDict_Values == 0)) goto LA301_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_Values");
	}
	LA301_: ;
	T303_ = (void*)0;
	T303_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyDict_Contains");
	(*pl).PyDict_Contains = ((tyProc__MTei9bsKjha0o1cISO9aLMDg) (T303_));
	{
		if (!((*pl).PyDict_Contains == 0)) goto LA306_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyDict_Contains");
	}
	LA306_: ;
	{
		if (!((*pl).pythonVersion == ((NI) 3))) goto LA310_;
		(*pl).PyDealloc = deallocPythonObj__g4g2BXzYUyHtyZiBrSD7aw;
	}
	goto LA308_;
	LA310_: ;
	{
		(*pl).PyDealloc = deallocPythonObj__g4g2BXzYUyHtyZiBrSD7aw;
	}
	LA308_: ;
	T313_ = (void*)0;
	T313_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_Clear");
	(*pl).PyErr_Clear = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T313_));
	{
		if (!((*pl).PyErr_Clear == 0)) goto LA316_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_Clear");
	}
	LA316_: ;
	T318_ = (void*)0;
	T318_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_SetString");
	(*pl).PyErr_SetString = ((tyProc__WYY8i0I79agBofnUcEGCfig) (T318_));
	{
		if (!((*pl).PyErr_SetString == 0)) goto LA321_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_SetString");
	}
	LA321_: ;
	T323_ = (void*)0;
	T323_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_Occurred");
	(*pl).PyErr_Occurred = ((tyProc__NzboHqZVJcbdtVGYrOosXQ) (T323_));
	{
		if (!((*pl).PyErr_Occurred == 0)) goto LA326_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_Occurred");
	}
	LA326_: ;
	T328_ = (void*)0;
	T328_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_TypeError");
	(*pl).PyExc_TypeError = ((void*) (T328_));
	{
		if (!((*pl).PyExc_TypeError == 0)) goto LA331_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_TypeError");
	}
	LA331_: ;
	(*pl).PyExc_TypeError = (*((void**) ((*pl).PyExc_TypeError)));
	T333_ = (void*)0;
	T333_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyCapsule_New");
	(*pl).PyCapsule_New = ((tyProc__jcEovQ2rZUNUsYxohT50Ug) (T333_));
	{
		if (!((*pl).PyCapsule_New == 0)) goto LA336_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyCapsule_New");
	}
	LA336_: ;
	T338_ = (void*)0;
	T338_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyCapsule_GetPointer");
	(*pl).PyCapsule_GetPointer = ((tyProc__YezmFzxOOyM9cb11Eoq1Elg) (T338_));
	{
		if (!((*pl).PyCapsule_GetPointer == 0)) goto LA341_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyCapsule_GetPointer");
	}
	LA341_: ;
	T343_ = (void*)0;
	T343_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyImport_ImportModule");
	(*pl).PyImport_ImportModule = ((tyProc__YDKrw1adv61oVQkQhbYyaA) (T343_));
	{
		if (!((*pl).PyImport_ImportModule == 0)) goto LA346_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyImport_ImportModule");
	}
	LA346_: ;
	T348_ = (void*)0;
	T348_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyEval_GetBuiltins");
	(*pl).PyEval_GetBuiltins = ((tyProc__NzboHqZVJcbdtVGYrOosXQ) (T348_));
	{
		if (!((*pl).PyEval_GetBuiltins == 0)) goto LA351_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyEval_GetBuiltins");
	}
	LA351_: ;
	T353_ = (void*)0;
	T353_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyEval_GetGlobals");
	(*pl).PyEval_GetGlobals = ((tyProc__NzboHqZVJcbdtVGYrOosXQ) (T353_));
	{
		if (!((*pl).PyEval_GetGlobals == 0)) goto LA356_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyEval_GetGlobals");
	}
	LA356_: ;
	T358_ = (void*)0;
	T358_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyEval_GetLocals");
	(*pl).PyEval_GetLocals = ((tyProc__NzboHqZVJcbdtVGYrOosXQ) (T358_));
	{
		if (!((*pl).PyEval_GetLocals == 0)) goto LA361_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyEval_GetLocals");
	}
	LA361_: ;
	T363_ = (void*)0;
	T363_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyCFunction_NewEx");
	(*pl).PyCFunction_NewEx = ((tyProc__9b2qzlf3LCKK0JvThQT1atg) (T363_));
	{
		if (!((*pl).PyCFunction_NewEx == 0)) goto LA366_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyCFunction_NewEx");
	}
	LA366_: ;
	T368_ = (void*)0;
	T368_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_Fetch");
	(*pl).PyErr_Fetch = ((tyProc__U0oVFt576Ze44Q9a3eZc5wg) (T368_));
	{
		if (!((*pl).PyErr_Fetch == 0)) goto LA371_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_Fetch");
	}
	LA371_: ;
	T373_ = (void*)0;
	T373_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_NormalizeException");
	(*pl).PyErr_NormalizeException = ((tyProc__U0oVFt576Ze44Q9a3eZc5wg) (T373_));
	{
		if (!((*pl).PyErr_NormalizeException == 0)) goto LA376_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_NormalizeException");
	}
	LA376_: ;
	T378_ = (void*)0;
	T378_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_GivenExceptionMatches");
	(*pl).PyErr_GivenExceptionMatches = ((tyProc__MTei9bsKjha0o1cISO9aLMDg) (T378_));
	{
		if (!((*pl).PyErr_GivenExceptionMatches == 0)) goto LA381_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_GivenExceptionMatches");
	}
	LA381_: ;
	T383_ = (void*)0;
	T383_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyErr_NewException");
	(*pl).PyErr_NewException = ((tyProc__BZ6N5NNdHcK05FTDxQbEWw) (T383_));
	{
		if (!((*pl).PyErr_NewException == 0)) goto LA386_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyErr_NewException");
	}
	LA386_: ;
	T388_ = (void*)0;
	T388_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_ArithmeticError");
	(*pl).PyExc_ArithmeticError = ((void*) (T388_));
	{
		if (!((*pl).PyExc_ArithmeticError == 0)) goto LA391_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_ArithmeticError");
	}
	LA391_: ;
	(*pl).PyExc_ArithmeticError = (*((void**) ((*pl).PyExc_ArithmeticError)));
	T393_ = (void*)0;
	T393_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_FloatingPointError");
	(*pl).PyExc_FloatingPointError = ((void*) (T393_));
	{
		if (!((*pl).PyExc_FloatingPointError == 0)) goto LA396_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_FloatingPointError");
	}
	LA396_: ;
	(*pl).PyExc_FloatingPointError = (*((void**) ((*pl).PyExc_FloatingPointError)));
	T398_ = (void*)0;
	T398_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_OverflowError");
	(*pl).PyExc_OverflowError = ((void*) (T398_));
	{
		if (!((*pl).PyExc_OverflowError == 0)) goto LA401_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_OverflowError");
	}
	LA401_: ;
	(*pl).PyExc_OverflowError = (*((void**) ((*pl).PyExc_OverflowError)));
	T403_ = (void*)0;
	T403_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_ZeroDivisionError");
	(*pl).PyExc_ZeroDivisionError = ((void*) (T403_));
	{
		if (!((*pl).PyExc_ZeroDivisionError == 0)) goto LA406_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_ZeroDivisionError");
	}
	LA406_: ;
	(*pl).PyExc_ZeroDivisionError = (*((void**) ((*pl).PyExc_ZeroDivisionError)));
	T408_ = (void*)0;
	T408_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_AssertionError");
	(*pl).PyExc_AssertionError = ((void*) (T408_));
	{
		if (!((*pl).PyExc_AssertionError == 0)) goto LA411_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_AssertionError");
	}
	LA411_: ;
	(*pl).PyExc_AssertionError = (*((void**) ((*pl).PyExc_AssertionError)));
	T413_ = (void*)0;
	T413_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_OSError");
	(*pl).PyExc_OSError = ((void*) (T413_));
	{
		if (!((*pl).PyExc_OSError == 0)) goto LA416_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_OSError");
	}
	LA416_: ;
	(*pl).PyExc_OSError = (*((void**) ((*pl).PyExc_OSError)));
	T418_ = (void*)0;
	T418_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_IOError");
	(*pl).PyExc_IOError = ((void*) (T418_));
	{
		if (!((*pl).PyExc_IOError == 0)) goto LA421_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_IOError");
	}
	LA421_: ;
	(*pl).PyExc_IOError = (*((void**) ((*pl).PyExc_IOError)));
	T423_ = (void*)0;
	T423_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_ValueError");
	(*pl).PyExc_ValueError = ((void*) (T423_));
	{
		if (!((*pl).PyExc_ValueError == 0)) goto LA426_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_ValueError");
	}
	LA426_: ;
	(*pl).PyExc_ValueError = (*((void**) ((*pl).PyExc_ValueError)));
	T428_ = (void*)0;
	T428_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_EOFError");
	(*pl).PyExc_EOFError = ((void*) (T428_));
	{
		if (!((*pl).PyExc_EOFError == 0)) goto LA431_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_EOFError");
	}
	LA431_: ;
	(*pl).PyExc_EOFError = (*((void**) ((*pl).PyExc_EOFError)));
	T433_ = (void*)0;
	T433_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_MemoryError");
	(*pl).PyExc_MemoryError = ((void*) (T433_));
	{
		if (!((*pl).PyExc_MemoryError == 0)) goto LA436_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_MemoryError");
	}
	LA436_: ;
	(*pl).PyExc_MemoryError = (*((void**) ((*pl).PyExc_MemoryError)));
	T438_ = (void*)0;
	T438_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_IndexError");
	(*pl).PyExc_IndexError = ((void*) (T438_));
	{
		if (!((*pl).PyExc_IndexError == 0)) goto LA441_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_IndexError");
	}
	LA441_: ;
	(*pl).PyExc_IndexError = (*((void**) ((*pl).PyExc_IndexError)));
	T443_ = (void*)0;
	T443_ = symAddr__ALH9bdNwXEzg7MPq4PA9csvw(m, "PyExc_KeyError");
	(*pl).PyExc_KeyError = ((void*) (T443_));
	{
		if (!((*pl).PyExc_KeyError == 0)) goto LA446_;
		symNotLoadedErr__bDtoj2GKRI9aw9bq59axC9b9aOw("PyExc_KeyError");
	}
	LA446_: ;
	(*pl).PyExc_KeyError = (*((void**) ((*pl).PyExc_KeyError)));
	return result;
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, registerExportedModule__2aw5dpL5lVZZ9cjH0apWcXA)(NimStringDesc* name, void* initAddr2, void* initAddr3) {	tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A T1_;
	NI T2_;
	nimZeroMem((void*)(&T1_), sizeof(tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A));
	nimZeroMem((void*)(&T1_), sizeof(tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A));
	T1_.name = copyString(name);
	T1_.initAddr2 = initAddr2;
	T1_.initAddr3 = initAddr3;
	exportedModules__8kMAOMTFJYz2QnlnegLbYw = (tySequence__M73GJ9bOx1XdoIRnhIyhqTQ*) incrSeqV3((TGenericSeq*)(exportedModules__8kMAOMTFJYz2QnlnegLbYw), (&NTI__M73GJ9bOx1XdoIRnhIyhqTQ_));
	T2_ = exportedModules__8kMAOMTFJYz2QnlnegLbYw->Sup.len++;
	exportedModules__8kMAOMTFJYz2QnlnegLbYw->data[T2_].name = copyString(T1_.name);
	exportedModules__8kMAOMTFJYz2QnlnegLbYw->data[T2_].initAddr2 = T1_.initAddr2;
	exportedModules__8kMAOMTFJYz2QnlnegLbYw->data[T2_].initAddr3 = T1_.initAddr3;
}
N_LIB_PRIVATE N_NIMCALL(void, nimpy_py_libInit000)(void) {
{

	nimRegisterGlobalMarker(TM__XnAUe69cYg8yQhnmiRJUnHw_3);


	nimRegisterGlobalMarker(TM__XnAUe69cYg8yQhnmiRJUnHw_5);

	exportedModules__8kMAOMTFJYz2QnlnegLbYw = NIM_NIL;
}
}

N_LIB_PRIVATE N_NIMCALL(void, nimpy_py_libDatInit000)(void) {
static TNimNode* TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[88];
static TNimNode* TM__XnAUe69cYg8yQhnmiRJUnHw_4_3[3];
static TNimNode TM__XnAUe69cYg8yQhnmiRJUnHw_0[93];
NTI__bTw708kK89b8Vj9cmSu9a4zig_.size = sizeof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig);
NTI__bTw708kK89b8Vj9cmSu9a4zig_.kind = 18;
NTI__bTw708kK89b8Vj9cmSu9a4zig_.base = 0;
NTI__bTw708kK89b8Vj9cmSu9a4zig_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[0] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[1];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[1].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[1].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, module);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[1].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[1].name = "module";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[1] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[2];
NTI__SsjMo29bx9bP5kwe2xgM3Scg_.size = sizeof(tyProc__SsjMo29bx9bP5kwe2xgM3Scg);
NTI__SsjMo29bx9bP5kwe2xgM3Scg_.kind = 25;
NTI__SsjMo29bx9bP5kwe2xgM3Scg_.base = 0;
NTI__SsjMo29bx9bP5kwe2xgM3Scg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[2].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[2].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, Py_BuildValue);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[2].typ = (&NTI__SsjMo29bx9bP5kwe2xgM3Scg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[2].name = "Py_BuildValue";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[2] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[3];
NTI__4wJmT85lsn175X0dPNQv7w_.size = sizeof(tyProc__4wJmT85lsn175X0dPNQv7w);
NTI__4wJmT85lsn175X0dPNQv7w_.kind = 25;
NTI__4wJmT85lsn175X0dPNQv7w_.base = 0;
NTI__4wJmT85lsn175X0dPNQv7w_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[3].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[3].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyTuple_New);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[3].typ = (&NTI__4wJmT85lsn175X0dPNQv7w_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[3].name = "PyTuple_New";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[3] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[4];
NTI__YRQqZC12s3573tRGP8MV3g_.size = sizeof(tyProc__YRQqZC12s3573tRGP8MV3g);
NTI__YRQqZC12s3573tRGP8MV3g_.kind = 25;
NTI__YRQqZC12s3573tRGP8MV3g_.base = 0;
NTI__YRQqZC12s3573tRGP8MV3g_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[4].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[4].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyTuple_Size);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[4].typ = (&NTI__YRQqZC12s3573tRGP8MV3g_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[4].name = "PyTuple_Size";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[4] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[5];
NTI__oPIasAghCTvCKmvkMeB1xQ_.size = sizeof(tyProc__oPIasAghCTvCKmvkMeB1xQ);
NTI__oPIasAghCTvCKmvkMeB1xQ_.kind = 25;
NTI__oPIasAghCTvCKmvkMeB1xQ_.base = 0;
NTI__oPIasAghCTvCKmvkMeB1xQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[5].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[5].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyTuple_GetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[5].typ = (&NTI__oPIasAghCTvCKmvkMeB1xQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[5].name = "PyTuple_GetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[5] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[6];
NTI__6slETyyIDJuDOSqkO0hUXA_.size = sizeof(tyProc__6slETyyIDJuDOSqkO0hUXA);
NTI__6slETyyIDJuDOSqkO0hUXA_.kind = 25;
NTI__6slETyyIDJuDOSqkO0hUXA_.base = 0;
NTI__6slETyyIDJuDOSqkO0hUXA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[6].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[6].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyTuple_SetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[6].typ = (&NTI__6slETyyIDJuDOSqkO0hUXA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[6].name = "PyTuple_SetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[6] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[7];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[7].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[7].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, Py_None);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[7].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[7].name = "Py_None";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[7] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[8];
NTI__tgpXIILGoVcO9bvYnz9azTVQ_.size = sizeof(tyProc__tgpXIILGoVcO9bvYnz9azTVQ);
NTI__tgpXIILGoVcO9bvYnz9azTVQ_.kind = 25;
NTI__tgpXIILGoVcO9bvYnz9azTVQ_.base = 0;
NTI__tgpXIILGoVcO9bvYnz9azTVQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[8].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[8].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyType_Ready);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[8].typ = (&NTI__tgpXIILGoVcO9bvYnz9azTVQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[8].name = "PyType_Ready";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[8] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[9];
NTI__eYT4U6bGFqFBUxk9b15mfOA_.size = sizeof(tyProc__eYT4U6bGFqFBUxk9b15mfOA);
NTI__eYT4U6bGFqFBUxk9b15mfOA_.kind = 25;
NTI__eYT4U6bGFqFBUxk9b15mfOA_.base = 0;
NTI__eYT4U6bGFqFBUxk9b15mfOA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[9].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[9].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyType_GenericNew);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[9].typ = (&NTI__eYT4U6bGFqFBUxk9b15mfOA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[9].name = "PyType_GenericNew";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[9] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[10];
NTI__T08W9bgbY4bOv2q64h6irpw_.size = sizeof(tyProc__T08W9bgbY4bOv2q64h6irpw);
NTI__T08W9bgbY4bOv2q64h6irpw_.kind = 25;
NTI__T08W9bgbY4bOv2q64h6irpw_.base = 0;
NTI__T08W9bgbY4bOv2q64h6irpw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[10].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[10].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyModule_AddObject);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[10].typ = (&NTI__T08W9bgbY4bOv2q64h6irpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[10].name = "PyModule_AddObject";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[10] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[11];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[11].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[11].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyList_New);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[11].typ = (&NTI__4wJmT85lsn175X0dPNQv7w_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[11].name = "PyList_New";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[11] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[12];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[12].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[12].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyList_Size);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[12].typ = (&NTI__YRQqZC12s3573tRGP8MV3g_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[12].name = "PyList_Size";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[12] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[13];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[13].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[13].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyList_GetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[13].typ = (&NTI__oPIasAghCTvCKmvkMeB1xQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[13].name = "PyList_GetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[13] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[14];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[14].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[14].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyList_SetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[14].typ = (&NTI__6slETyyIDJuDOSqkO0hUXA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[14].name = "PyList_SetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[14] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[15];
NTI__uQWqJp3WAx8fOY1h9aCwjIg_.size = sizeof(tyProc__uQWqJp3WAx8fOY1h9aCwjIg);
NTI__uQWqJp3WAx8fOY1h9aCwjIg_.kind = 25;
NTI__uQWqJp3WAx8fOY1h9aCwjIg_.base = 0;
NTI__uQWqJp3WAx8fOY1h9aCwjIg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[15].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[15].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_Call);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[15].typ = (&NTI__uQWqJp3WAx8fOY1h9aCwjIg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[15].name = "PyObject_Call";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[15] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[16];
NTI__fbYpjfe38x3ujjAmVRbI1Q_.size = sizeof(tyProc__fbYpjfe38x3ujjAmVRbI1Q);
NTI__fbYpjfe38x3ujjAmVRbI1Q_.kind = 25;
NTI__fbYpjfe38x3ujjAmVRbI1Q_.base = 0;
NTI__fbYpjfe38x3ujjAmVRbI1Q_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[16].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[16].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_IsTrue);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[16].typ = (&NTI__fbYpjfe38x3ujjAmVRbI1Q_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[16].name = "PyObject_IsTrue";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[16] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[17];
NTI__YezmFzxOOyM9cb11Eoq1Elg_.size = sizeof(tyProc__YezmFzxOOyM9cb11Eoq1Elg);
NTI__YezmFzxOOyM9cb11Eoq1Elg_.kind = 25;
NTI__YezmFzxOOyM9cb11Eoq1Elg_.base = 0;
NTI__YezmFzxOOyM9cb11Eoq1Elg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[17].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[17].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_GetAttrString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[17].typ = (&NTI__YezmFzxOOyM9cb11Eoq1Elg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[17].name = "PyObject_GetAttrString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[17] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[18];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[18].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[18].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_SetAttrString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[18].typ = (&NTI__T08W9bgbY4bOv2q64h6irpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[18].name = "PyObject_SetAttrString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[18] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[19];
NTI__jvPpjMAkI9bwM1B9apOphnlA_.size = sizeof(tyProc__jvPpjMAkI9bwM1B9apOphnlA);
NTI__jvPpjMAkI9bwM1B9apOphnlA_.kind = 25;
NTI__jvPpjMAkI9bwM1B9apOphnlA_.base = 0;
NTI__jvPpjMAkI9bwM1B9apOphnlA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[19].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[19].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_Dir);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[19].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[19].name = "PyObject_Dir";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[19] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[20];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[20].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[20].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_Str);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[20].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[20].name = "PyObject_Str";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[20] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[21];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[21].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[21].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_GetIter);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[21].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[21].name = "PyObject_GetIter";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[21] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[22];
NTI__VQ1ysQk017myXMGb79cPTVw_.size = sizeof(tyProc__VQ1ysQk017myXMGb79cPTVw);
NTI__VQ1ysQk017myXMGb79cPTVw_.kind = 25;
NTI__VQ1ysQk017myXMGb79cPTVw_.base = 0;
NTI__VQ1ysQk017myXMGb79cPTVw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[22].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[22].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_GetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[22].typ = (&NTI__VQ1ysQk017myXMGb79cPTVw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[22].name = "PyObject_GetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[22] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[23];
NTI__7LMjBc4zOHVIsNdulNv7QQ_.size = sizeof(tyProc__7LMjBc4zOHVIsNdulNv7QQ);
NTI__7LMjBc4zOHVIsNdulNv7QQ_.kind = 25;
NTI__7LMjBc4zOHVIsNdulNv7QQ_.base = 0;
NTI__7LMjBc4zOHVIsNdulNv7QQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[23].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[23].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_SetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[23].typ = (&NTI__7LMjBc4zOHVIsNdulNv7QQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[23].name = "PyObject_SetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[23] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[24];
NTI__eoRP3F9aLT3mtHj6OkcMSyQ_.size = sizeof(tyProc__eoRP3F9aLT3mtHj6OkcMSyQ);
NTI__eoRP3F9aLT3mtHj6OkcMSyQ_.kind = 25;
NTI__eoRP3F9aLT3mtHj6OkcMSyQ_.base = 0;
NTI__eoRP3F9aLT3mtHj6OkcMSyQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[24].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[24].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_RichCompareBool);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[24].typ = (&NTI__eoRP3F9aLT3mtHj6OkcMSyQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[24].name = "PyObject_RichCompareBool";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[24] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[25];
NTI__8hR9arLDkUs9ag3Pt9bWtjfsg_.size = sizeof(tyProc__8hR9arLDkUs9ag3Pt9bWtjfsg);
NTI__8hR9arLDkUs9ag3Pt9bWtjfsg_.kind = 25;
NTI__8hR9arLDkUs9ag3Pt9bWtjfsg_.base = 0;
NTI__8hR9arLDkUs9ag3Pt9bWtjfsg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[25].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[25].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyObject_GetBuffer);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[25].typ = (&NTI__8hR9arLDkUs9ag3Pt9bWtjfsg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[25].name = "PyObject_GetBuffer";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[25] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[26];
NTI__vFvpnKOere9bRFN9czzMRlTA_.size = sizeof(tyProc__vFvpnKOere9bRFN9czzMRlTA);
NTI__vFvpnKOere9bRFN9czzMRlTA_.kind = 25;
NTI__vFvpnKOere9bRFN9czzMRlTA_.base = 0;
NTI__vFvpnKOere9bRFN9czzMRlTA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[26].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[26].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyBuffer_Release);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[26].typ = (&NTI__vFvpnKOere9bRFN9czzMRlTA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[26].name = "PyBuffer_Release";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[26] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[27];
NTI__BZ6N5NNdHcK05FTDxQbEWw_.size = sizeof(tyProc__BZ6N5NNdHcK05FTDxQbEWw);
NTI__BZ6N5NNdHcK05FTDxQbEWw_.kind = 25;
NTI__BZ6N5NNdHcK05FTDxQbEWw_.base = 0;
NTI__BZ6N5NNdHcK05FTDxQbEWw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[27].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[27].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_NewException);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[27].typ = (&NTI__BZ6N5NNdHcK05FTDxQbEWw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[27].name = "PyErr_NewException";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[27] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[28];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[28].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[28].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyIter_Next);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[28].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[28].name = "PyIter_Next";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[28] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[29];
NTI__mIlNZ9aGaphVJCyIIofK8mg_.size = sizeof(tyProc__mIlNZ9aGaphVJCyIIofK8mg);
NTI__mIlNZ9aGaphVJCyIIofK8mg_.kind = 25;
NTI__mIlNZ9aGaphVJCyIIofK8mg_.base = 0;
NTI__mIlNZ9aGaphVJCyIIofK8mg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[29].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[29].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyLong_AsLongLong);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[29].typ = (&NTI__mIlNZ9aGaphVJCyIIofK8mg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[29].name = "PyLong_AsLongLong";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[29] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[30];
NTI__2su9b9chqHYibM7sMkbSaSkA_.size = sizeof(tyProc__2su9b9chqHYibM7sMkbSaSkA);
NTI__2su9b9chqHYibM7sMkbSaSkA_.kind = 25;
NTI__2su9b9chqHYibM7sMkbSaSkA_.base = 0;
NTI__2su9b9chqHYibM7sMkbSaSkA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[30].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[30].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyFloat_AsDouble);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[30].typ = (&NTI__2su9b9chqHYibM7sMkbSaSkA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[30].name = "PyFloat_AsDouble";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[30] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[31];
NTI__Fc4ZUx59aQs10dLxeMQ50mw_.size = sizeof(tyProc__Fc4ZUx59aQs10dLxeMQ50mw);
NTI__Fc4ZUx59aQs10dLxeMQ50mw_.kind = 25;
NTI__Fc4ZUx59aQs10dLxeMQ50mw_.base = 0;
NTI__Fc4ZUx59aQs10dLxeMQ50mw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[31].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[31].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyBool_FromLong);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[31].typ = (&NTI__Fc4ZUx59aQs10dLxeMQ50mw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[31].name = "PyBool_FromLong";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[31] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[32];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[32].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[32].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyFloat_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[32].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[32].name = "PyFloat_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[32] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[33];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[33].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[33].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyComplex_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[33].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[33].name = "PyComplex_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[33] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[34];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[34].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[34].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyCapsule_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[34].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[34].name = "PyCapsule_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[34] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[35];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[35].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[35].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyTuple_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[35].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[35].name = "PyTuple_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[35] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[36];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[36].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[36].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyList_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[36].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[36].name = "PyList_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[36] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[37];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[37].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[37].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyBytes_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[37].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[37].name = "PyBytes_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[37] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[38];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[38].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[38].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyUnicode_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[38].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[38].name = "PyUnicode_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[38] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[39];
NTI__i2exZ7Vtp648U9crOFcq9beQ_.size = sizeof(tyProc__i2exZ7Vtp648U9crOFcq9beQ);
NTI__i2exZ7Vtp648U9crOFcq9beQ_.kind = 25;
NTI__i2exZ7Vtp648U9crOFcq9beQ_.base = 0;
NTI__i2exZ7Vtp648U9crOFcq9beQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[39].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[39].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyType_IsSubtype);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[39].typ = (&NTI__i2exZ7Vtp648U9crOFcq9beQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[39].name = "PyType_IsSubtype";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[39] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[40];
NTI__N1A5ZvDSgO9c9aRXmVqfn9bAw_.size = sizeof(tyProc__N1A5ZvDSgO9c9aRXmVqfn9bAw);
NTI__N1A5ZvDSgO9c9aRXmVqfn9bAw_.kind = 25;
NTI__N1A5ZvDSgO9c9aRXmVqfn9bAw_.base = 0;
NTI__N1A5ZvDSgO9c9aRXmVqfn9bAw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[40].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[40].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyComplex_AsCComplex);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[40].typ = (&NTI__N1A5ZvDSgO9c9aRXmVqfn9bAw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[40].name = "PyComplex_AsCComplex";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[40] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[41];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[41].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[41].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyComplex_RealAsDouble);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[41].typ = (&NTI__2su9b9chqHYibM7sMkbSaSkA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[41].name = "PyComplex_RealAsDouble";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[41] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[42];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[42].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[42].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyComplex_ImagAsDouble);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[42].typ = (&NTI__2su9b9chqHYibM7sMkbSaSkA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[42].name = "PyComplex_ImagAsDouble";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[42] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[43];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[43].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[43].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyUnicode_AsUTF8String);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[43].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[43].name = "PyUnicode_AsUTF8String";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[43] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[44];
NTI__3FKLKFzOaK7FD6dRLWM6Jw_.size = sizeof(tyProc__3FKLKFzOaK7FD6dRLWM6Jw);
NTI__3FKLKFzOaK7FD6dRLWM6Jw_.kind = 25;
NTI__3FKLKFzOaK7FD6dRLWM6Jw_.base = 0;
NTI__3FKLKFzOaK7FD6dRLWM6Jw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[44].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[44].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyBytes_AsStringAndSize);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[44].typ = (&NTI__3FKLKFzOaK7FD6dRLWM6Jw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[44].name = "PyBytes_AsStringAndSize";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[44] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[45];
NTI__YDKrw1adv61oVQkQhbYyaA_.size = sizeof(tyProc__YDKrw1adv61oVQkQhbYyaA);
NTI__YDKrw1adv61oVQkQhbYyaA_.kind = 25;
NTI__YDKrw1adv61oVQkQhbYyaA_.base = 0;
NTI__YDKrw1adv61oVQkQhbYyaA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[45].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[45].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyUnicode_FromString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[45].typ = (&NTI__YDKrw1adv61oVQkQhbYyaA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[45].name = "PyUnicode_FromString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[45] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[46];
NTI__B2MjSeo07a72ynTQRVYFKw_.size = sizeof(tyProc__B2MjSeo07a72ynTQRVYFKw);
NTI__B2MjSeo07a72ynTQRVYFKw_.kind = 25;
NTI__B2MjSeo07a72ynTQRVYFKw_.base = 0;
NTI__B2MjSeo07a72ynTQRVYFKw_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[46].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[46].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyUnicode_CompareWithASCIIString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[46].typ = (&NTI__B2MjSeo07a72ynTQRVYFKw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[46].name = "PyUnicode_CompareWithASCIIString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[46] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[47];
NTI__p1X2BwWx9a3wsChhykvf29aA_.size = sizeof(tyProc__p1X2BwWx9a3wsChhykvf29aA);
NTI__p1X2BwWx9a3wsChhykvf29aA_.kind = 25;
NTI__p1X2BwWx9a3wsChhykvf29aA_.base = 0;
NTI__p1X2BwWx9a3wsChhykvf29aA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[47].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[47].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyString_AsString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[47].typ = (&NTI__p1X2BwWx9a3wsChhykvf29aA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[47].name = "PyString_AsString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[47] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[48];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[48].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[48].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_Type);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[48].typ = (&NTI__dgEY47TsFEQv355iEJP9bPA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[48].name = "PyDict_Type";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[48] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[49];
NTI__NzboHqZVJcbdtVGYrOosXQ_.size = sizeof(tyProc__NzboHqZVJcbdtVGYrOosXQ);
NTI__NzboHqZVJcbdtVGYrOosXQ_.kind = 25;
NTI__NzboHqZVJcbdtVGYrOosXQ_.base = 0;
NTI__NzboHqZVJcbdtVGYrOosXQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[49].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[49].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_New);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[49].typ = (&NTI__NzboHqZVJcbdtVGYrOosXQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[49].name = "PyDict_New";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[49] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[50];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[50].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[50].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_Size);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[50].typ = (&NTI__YRQqZC12s3573tRGP8MV3g_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[50].name = "PyDict_Size";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[50] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[51];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[51].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[51].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_GetItemString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[51].typ = (&NTI__YezmFzxOOyM9cb11Eoq1Elg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[51].name = "PyDict_GetItemString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[51] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[52];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[52].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[52].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_SetItemString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[52].typ = (&NTI__T08W9bgbY4bOv2q64h6irpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[52].name = "PyDict_SetItemString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[52] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[53];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[53].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[53].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_GetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[53].typ = (&NTI__VQ1ysQk017myXMGb79cPTVw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[53].name = "PyDict_GetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[53] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[54];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[54].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[54].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_SetItem);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[54].typ = (&NTI__7LMjBc4zOHVIsNdulNv7QQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[54].name = "PyDict_SetItem";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[54] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[55];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[55].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[55].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_Keys);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[55].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[55].name = "PyDict_Keys";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[55] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[56];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[56].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[56].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_Values);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[56].typ = (&NTI__jvPpjMAkI9bwM1B9apOphnlA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[56].name = "PyDict_Values";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[56] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[57];
NTI__MTei9bsKjha0o1cISO9aLMDg_.size = sizeof(tyProc__MTei9bsKjha0o1cISO9aLMDg);
NTI__MTei9bsKjha0o1cISO9aLMDg_.kind = 25;
NTI__MTei9bsKjha0o1cISO9aLMDg_.base = 0;
NTI__MTei9bsKjha0o1cISO9aLMDg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[57].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[57].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDict_Contains);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[57].typ = (&NTI__MTei9bsKjha0o1cISO9aLMDg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[57].name = "PyDict_Contains";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[57] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[58];
NTI__4SVlZZPmetqBimNsH9cHcOA_.size = sizeof(tyProc__4SVlZZPmetqBimNsH9cHcOA);
NTI__4SVlZZPmetqBimNsH9cHcOA_.kind = 25;
NTI__4SVlZZPmetqBimNsH9cHcOA_.base = 0;
NTI__4SVlZZPmetqBimNsH9cHcOA_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[58].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[58].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyDealloc);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[58].typ = (&NTI__4SVlZZPmetqBimNsH9cHcOA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[58].name = "PyDealloc";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[58] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[59];
NTI__ln4kdL5W9bbX4a1xl8nnVXQ_.size = sizeof(tyProc__ln4kdL5W9bbX4a1xl8nnVXQ);
NTI__ln4kdL5W9bbX4a1xl8nnVXQ_.kind = 25;
NTI__ln4kdL5W9bbX4a1xl8nnVXQ_.base = 0;
NTI__ln4kdL5W9bbX4a1xl8nnVXQ_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[59].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[59].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_Clear);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[59].typ = (&NTI__ln4kdL5W9bbX4a1xl8nnVXQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[59].name = "PyErr_Clear";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[59] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[60];
NTI__WYY8i0I79agBofnUcEGCfig_.size = sizeof(tyProc__WYY8i0I79agBofnUcEGCfig);
NTI__WYY8i0I79agBofnUcEGCfig_.kind = 25;
NTI__WYY8i0I79agBofnUcEGCfig_.base = 0;
NTI__WYY8i0I79agBofnUcEGCfig_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[60].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[60].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_SetString);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[60].typ = (&NTI__WYY8i0I79agBofnUcEGCfig_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[60].name = "PyErr_SetString";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[60] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[61];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[61].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[61].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_Occurred);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[61].typ = (&NTI__NzboHqZVJcbdtVGYrOosXQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[61].name = "PyErr_Occurred";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[61] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[62];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[62].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[62].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_TypeError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[62].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[62].name = "PyExc_TypeError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[62] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[63];
NTI__jcEovQ2rZUNUsYxohT50Ug_.size = sizeof(tyProc__jcEovQ2rZUNUsYxohT50Ug);
NTI__jcEovQ2rZUNUsYxohT50Ug_.kind = 25;
NTI__jcEovQ2rZUNUsYxohT50Ug_.base = 0;
NTI__jcEovQ2rZUNUsYxohT50Ug_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[63].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[63].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyCapsule_New);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[63].typ = (&NTI__jcEovQ2rZUNUsYxohT50Ug_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[63].name = "PyCapsule_New";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[63] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[64];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[64].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[64].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyCapsule_GetPointer);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[64].typ = (&NTI__YezmFzxOOyM9cb11Eoq1Elg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[64].name = "PyCapsule_GetPointer";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[64] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[65];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[65].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[65].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyImport_ImportModule);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[65].typ = (&NTI__YDKrw1adv61oVQkQhbYyaA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[65].name = "PyImport_ImportModule";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[65] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[66];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[66].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[66].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyEval_GetBuiltins);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[66].typ = (&NTI__NzboHqZVJcbdtVGYrOosXQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[66].name = "PyEval_GetBuiltins";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[66] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[67];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[67].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[67].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyEval_GetGlobals);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[67].typ = (&NTI__NzboHqZVJcbdtVGYrOosXQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[67].name = "PyEval_GetGlobals";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[67] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[68];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[68].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[68].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyEval_GetLocals);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[68].typ = (&NTI__NzboHqZVJcbdtVGYrOosXQ_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[68].name = "PyEval_GetLocals";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[68] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[69];
NTI__9b2qzlf3LCKK0JvThQT1atg_.size = sizeof(tyProc__9b2qzlf3LCKK0JvThQT1atg);
NTI__9b2qzlf3LCKK0JvThQT1atg_.kind = 25;
NTI__9b2qzlf3LCKK0JvThQT1atg_.base = 0;
NTI__9b2qzlf3LCKK0JvThQT1atg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[69].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[69].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyCFunction_NewEx);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[69].typ = (&NTI__9b2qzlf3LCKK0JvThQT1atg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[69].name = "PyCFunction_NewEx";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[69] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[70];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[70].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[70].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, pythonVersion);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[70].typ = (&NTI__rR5Bzr1D5krxoo1NcNyeMA_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[70].name = "pythonVersion";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[70] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[71];
NTI__U0oVFt576Ze44Q9a3eZc5wg_.size = sizeof(tyProc__U0oVFt576Ze44Q9a3eZc5wg);
NTI__U0oVFt576Ze44Q9a3eZc5wg_.kind = 25;
NTI__U0oVFt576Ze44Q9a3eZc5wg_.base = 0;
NTI__U0oVFt576Ze44Q9a3eZc5wg_.flags = 3;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[71].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[71].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_Fetch);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[71].typ = (&NTI__U0oVFt576Ze44Q9a3eZc5wg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[71].name = "PyErr_Fetch";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[71] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[72];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[72].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[72].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_NormalizeException);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[72].typ = (&NTI__U0oVFt576Ze44Q9a3eZc5wg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[72].name = "PyErr_NormalizeException";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[72] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[73];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[73].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[73].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyErr_GivenExceptionMatches);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[73].typ = (&NTI__MTei9bsKjha0o1cISO9aLMDg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[73].name = "PyErr_GivenExceptionMatches";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[73] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[74];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[74].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[74].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_BaseException);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[74].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[74].name = "PyExc_BaseException";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[74] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[75];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[75].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[75].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_Exception);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[75].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[75].name = "PyExc_Exception";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[75] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[76];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[76].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[76].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_ArithmeticError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[76].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[76].name = "PyExc_ArithmeticError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[76] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[77];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[77].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[77].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_FloatingPointError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[77].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[77].name = "PyExc_FloatingPointError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[77] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[78];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[78].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[78].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_OverflowError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[78].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[78].name = "PyExc_OverflowError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[78] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[79];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[79].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[79].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_ZeroDivisionError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[79].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[79].name = "PyExc_ZeroDivisionError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[79] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[80];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[80].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[80].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_AssertionError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[80].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[80].name = "PyExc_AssertionError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[80] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[81];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[81].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[81].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_OSError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[81].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[81].name = "PyExc_OSError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[81] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[82];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[82].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[82].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_IOError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[82].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[82].name = "PyExc_IOError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[82] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[83];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[83].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[83].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_ValueError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[83].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[83].name = "PyExc_ValueError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[83] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[84];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[84].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[84].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_EOFError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[84].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[84].name = "PyExc_EOFError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[84] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[85];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[85].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[85].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_MemoryError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[85].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[85].name = "PyExc_MemoryError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[85] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[86];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[86].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[86].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_IndexError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[86].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[86].name = "PyExc_IndexError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[86] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[87];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[87].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[87].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, PyExc_KeyError);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[87].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[87].name = "PyExc_KeyError";
TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[87] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[88];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[88].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[88].offset = offsetof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig, NimPyException);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[88].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[88].name = "NimPyException";
TM__XnAUe69cYg8yQhnmiRJUnHw_0[0].len = 88; TM__XnAUe69cYg8yQhnmiRJUnHw_0[0].kind = 2; TM__XnAUe69cYg8yQhnmiRJUnHw_0[0].sons = &TM__XnAUe69cYg8yQhnmiRJUnHw_2_88[0];
NTI__bTw708kK89b8Vj9cmSu9a4zig_.node = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[0];
NTI__cCIKHidpwSneftqUUnSNWg_.size = sizeof(tyObject_PyLibcolonObjectType___bTw708kK89b8Vj9cmSu9a4zig*);
NTI__cCIKHidpwSneftqUUnSNWg_.kind = 22;
NTI__cCIKHidpwSneftqUUnSNWg_.base = (&NTI__bTw708kK89b8Vj9cmSu9a4zig_);
NTI__cCIKHidpwSneftqUUnSNWg_.flags = 2;
NTI__cCIKHidpwSneftqUUnSNWg_.marker = Marker_tyRef__cCIKHidpwSneftqUUnSNWg;
NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_.size = sizeof(tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A);
NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_.kind = 18;
NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_.base = 0;
NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_.flags = 2;
TM__XnAUe69cYg8yQhnmiRJUnHw_4_3[0] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[90];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[90].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[90].offset = offsetof(tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A, name);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[90].typ = (&NTI__77mFvmsOLKik79ci2hXkHEg_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[90].name = "name";
TM__XnAUe69cYg8yQhnmiRJUnHw_4_3[1] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[91];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[91].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[91].offset = offsetof(tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A, initAddr2);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[91].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[91].name = "initAddr2";
TM__XnAUe69cYg8yQhnmiRJUnHw_4_3[2] = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[92];
TM__XnAUe69cYg8yQhnmiRJUnHw_0[92].kind = 1;
TM__XnAUe69cYg8yQhnmiRJUnHw_0[92].offset = offsetof(tyObject_ExportedModule__fxDBwb9c9c8NsdRe9bmg8Q9a2A, initAddr3);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[92].typ = (&NTI__vr5DoT1jILTGdRlYv1OYpw_);
TM__XnAUe69cYg8yQhnmiRJUnHw_0[92].name = "initAddr3";
TM__XnAUe69cYg8yQhnmiRJUnHw_0[89].len = 3; TM__XnAUe69cYg8yQhnmiRJUnHw_0[89].kind = 2; TM__XnAUe69cYg8yQhnmiRJUnHw_0[89].sons = &TM__XnAUe69cYg8yQhnmiRJUnHw_4_3[0];
NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_.node = &TM__XnAUe69cYg8yQhnmiRJUnHw_0[89];
NTI__M73GJ9bOx1XdoIRnhIyhqTQ_.size = sizeof(tySequence__M73GJ9bOx1XdoIRnhIyhqTQ*);
NTI__M73GJ9bOx1XdoIRnhIyhqTQ_.kind = 24;
NTI__M73GJ9bOx1XdoIRnhIyhqTQ_.base = (&NTI__fxDBwb9c9c8NsdRe9bmg8Q9a2A_);
NTI__M73GJ9bOx1XdoIRnhIyhqTQ_.flags = 2;
NTI__M73GJ9bOx1XdoIRnhIyhqTQ_.marker = Marker_tySequence__M73GJ9bOx1XdoIRnhIyhqTQ;
}

