/* Generated by Nim Compiler v1.0.6 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
int MAP_POPULATE__VA0iC4AP6fJAacff09cx89ag;
N_LIB_PRIVATE N_NIMCALL(void, stdlib_posixInit000)(void) {
{
	MAP_POPULATE__VA0iC4AP6fJAacff09cx89ag = ((int) 0);
}
}

